### PR TITLE
Added support for OSC routing options

### PR DESCRIPTION
**Pull request by fabianoboril**
When using routing options (routeStrategy) for route waypoints in OSC,
shortest and fastest will be treated differently.

Shortest = direct connection between A and B
Others = shortest path along the road network from A to B

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/677)

### CODE REVIEW

**Review by fpasch — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/677)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @fpasch and @glopezdiest)

**Review by fpasch — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Review by glopezdiest — APPROVED** [review]
EDIT: missclicked

**Review by glopezdiest — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/677)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
