### PR TITLE
Overwrite ParameterDeclarations from CLI arguments.

### PR DESCRIPTION
**Pull request by 80avin**
Checklist:

  - [x] Your branch is up-to-date with the `master` branch and tested with latest changes
  - [x] Extended the README / documentation, if necessary
  - [x] Code compiles correctly and runs
  - [x] Code is formatted and checked with Utilities/code_check_and_formatting.sh
  - [ ] Changelog is updated - ***not needed, since not a new release***

#### Description

New:
Added `--openscenarioparams` parameter to scene_runner, which overwrites the global ParameterDeclaration.
Syntax: 
```bash
python scenario_runner.py --openscenario <path/to/xosc-file> --openscenarioparams 'param1: value1, param2: value2'
```
Change: 
openscenario_parser.py: `additional_parameter_dict` argument of set_parameters overwrites those found in XML, in case of conflict.
#### Where has this been tested?

  * **Platform(s):*Ubuntu 18.04*
  * **Python version(s):*2, 3*

#### Possible Drawbacks
openscenario_parser.py: `additional_parameter_dict` argument of set_parameters overwrites those found in XML, in case of conflict.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)* status: all files reviewed, 3 unresolved discussions (waiting on @80avin)

___
*[scenario_runner.py, line 482 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_kTl4-m91XeQaZUQl:-MV_kTl4-m91XeQaZUQm:b66shmt) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/scenario_runner.py#L482)):*
> ```Python
>             return False
> 
>         openscenario_params = dict()
> ```

Can you please extend the CHANGELOG in docs/?
___
*[scenario_runner.py, line 537 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_jyAw5EPnZdIAuy40:-MV_jyAw5EPnZdIAuy41:b-xs9gld) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/scenario_runner.py#L537)):*
> ```Python
>         '--scenario', help='Name of the scenario to be executed. Use the preposition \'group:\' to run all scenarios of one class, e.g. ControlLoss or FollowLeadingVehicle')
>     parser.add_argument('--openscenario', help='Provide an OpenSCENARIO definition')
>     parser.add_argument('--openscenarioparams', help='Overwrited for OpenSCENARIO ParameterDeclaration')
> ```

Can you add a check that --openscenarioparams requires openscenario argument as well?
___
*[srunner/scenarioconfigs/openscenario_configuration.py, line 38 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_kAuN4LskvRY6fUQa:-MV_kAuN4LskvRY6fUQb:b3jf19k) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/srunner/scenarioconfigs/openscenario_configuration.py#L38)):*
> ```Python
>         self.xml_tree = ET.parse(filename)
>         self.filename = filename
>         self._custom_params = custom_params if custom_params is not None else dict()
> ```

Given that you provide always a dict() (empty or filled), we can exclude this if part, or not?

**Comment by fabianoboril** [comment]
Hi,
this is an awesome PR. I really like it. Could you please take care of the two small comments I made in the review? Thx.

**Comment by 80avin** [comment]
> Can you please extend the CHANGELOG in docs/?

Sure, I will

> Can you add a check that --openscenarioparams requires openscenario argument as well?

Not sure how this should be handled. I expect the script should ignore (with a warning or silently) the `--openscenarioparams` if `--openscenario` isn't specified. It is already silently ignoring it, but I can add a warning. Terminating the execution might not be the best thing to do in this case.

> Given that you provide always a dict() (empty or filled), we can exclude this if part, or not?

I found it cleaner to initialize the custom_params in the `__init__` function by a default value. This way, we can avoid handling special cases of `_custom_params is None` in other member functions.

**Review by 80avin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @fabianoboril)

___
*[scenario_runner.py, line 482 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_kTl4-m91XeQaZUQl:-MV_y1yW8QvNDQ5DgCs3:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/scenario_runner.py#L482)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can you please extend the CHANGELOG in docs/?
</blockquote></details>

Done.
___
*[scenario_runner.py, line 537 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_jyAw5EPnZdIAuy40:-MV_yB4U7K66aVFRk1_W:bri2k38) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/scenario_runner.py#L537)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can you add a check that --openscenarioparams requires openscenario argument as well?
</blockquote></details>

Done.
Added a warning.
___
*[srunner/scenarioconfigs/openscenario_configuration.py, line 38 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/736#-MV_kAuN4LskvRY6fUQa:-MV_yUX85cXuOvE4Ho2b:b-fn51gq) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/764deb5c4c430f639998601917184a5f52e2e46c/srunner/scenarioconfigs/openscenario_configuration.py#L38)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Given that you provide always a dict() (empty or filled), we can exclude this if part, or not?
</blockquote></details>

I found it cleaner to initialize the custom_params in the `__init__` function by a default value. This way, we can avoid handling special cases of `self._custom_params is None` in other member functions.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @fabianoboril)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/736)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @80avin)

**Pull request merged**
