### PR TITLE
Added support for OSC SynchronizeAction

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

This PR adds support to [OpenSCENARIO's SynchronizeAction](https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/SynchronizeAction.html) and adds an example *IntersectionCollisionAvoidance.xosc* that utilizes this behavior to force the ego vehicle to brake when entering an intersection.

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24
  * **CARLA version:** 0.9.10.1

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/689)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/689)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @fabianoboril and @glopezdiest)

___
*[srunner/scenarios/open_scenario.py, line 310 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/689#-MN2VY_VCMbEV8Mhhk8F:-MN2VY_VCMbEV8Mhhk8G:bbrxn7g) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/08bd1c9d5a0c2f61a05118ab5632a988197a2786/srunner/scenarios/open_scenario.py#L310)):*
> ```Python
>                                     for actor_id in actor_ids:
>                                         maneuver_behavior = OpenScenarioParser.convert_maneuver_to_atomic(
>                                             child, joint_actor_list[actor_id], joint_actor_list, self.config.catalogs)
> ```

Be careful: This may break many things in the OSCParser...
___
*[srunner/tools/openscenario_parser.py, line 992 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/689#-MN2VNt3B989TDyySUC5:-MN2VNt3B989TDyySUC6:b8jmrx) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/08bd1c9d5a0c2f61a05118ab5632a988197a2786/srunner/tools/openscenario_parser.py#L992)):*
> ```Python
>                             "AbsoluteTargetSpeed").attrib.get('value', 0))
>                         atomic = ChangeActorTargetSpeed(
>                             actor, target_speed, distance=distance, duration=duration, name=maneuver_name)
> ```

Changing the method to use actor_list as input, will break these behaviors.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/689)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @fabianoboril and @glopezdiest)

___
*[srunner/tools/openscenario_parser.py, line 992 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/689#-MN2VNt3B989TDyySUC5:-MNNKM4h1cQjqBi1hNmn:b-uc8239) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/08bd1c9d5a0c2f61a05118ab5632a988197a2786/srunner/tools/openscenario_parser.py#L992)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Changing the method to use actor_list as input, will break these behaviors.
</blockquote></details>

How so? I can't seem to see the reason

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/689)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[srunner/tools/openscenario_parser.py, line 992 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/689#-MN2VNt3B989TDyySUC5:-MNbiK2-4qOFh8RKyD7G:bjvruw7) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/08bd1c9d5a0c2f61a05118ab5632a988197a2786/srunner/tools/openscenario_parser.py#L992)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

How so? I can't seem to see the reason
</blockquote></details>

Oh sorry... I haven't seen that the list is an additional argument, not a replacement

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/689)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

**Pull request merged**
