### PR TITLE
Extended lane changes capabilities

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

Extended the lane changes capabilities so that multiple-lane lane changes are possible. This affects both the _LaneChangeAction_ at OSC as well as the _LaneChange_ atomic.

Failed lane changes no longer break the simulation, but correctly stop it instead

Fixed bug causing the ChangeLane scenario to never end.

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24
  * **CARLA version:** current master (0.9.10 pre release)

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/624)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
Let me also do a test before we merge the code...

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/624#-:-MGD2xCn6ajdTBAOr7Gj:b-os6ak)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 734 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/624#-MGCXGPa1u-XcmgfkoCZ:-MGCXGPb889YOUZt6qgH:bqm8iih) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/28bc62c0c4908e3138950c82f4e79f3066e6f69a/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L734)):*
> ```Python
> 
>         if not self._pos_before_lane_change:
>             self._pos_before_lane_change = current_position_actor.transform.location
> ```

This changes the behavior. Intended?
The original behavior updated the _pos_before_lane_change, until the vehicle was in the new lane (which could take a bit, depending on the speed). The new behavior updates _pos_before_lane_change only once, i.e. it will terminate sooner!

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/624)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 734 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/624#-MGCXGPa1u-XcmgfkoCZ:-MGD8tti8fN6AAG2yB-K:bk51fo9) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/28bc62c0c4908e3138950c82f4e79f3066e6f69a/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L734)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This changes the behavior. Intended?
The original behavior updated the _pos_before_lane_change, until the vehicle was in the new lane (which could take a bit, depending on the speed). The new behavior updates _pos_before_lane_change only once, i.e. it will terminate sooner!
</blockquote></details>

Oh, I think I missunderstood its utility then. I actually changed it to avoid the behavior from braking when the lane change was impossible, but as we aren't going there, I can change it back to how it was. I'm gonna do some tests.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/624)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 734 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/624#-MGCXGPa1u-XcmgfkoCZ:-MGDDQ11EbNWN6d9fpQZ:b-5vumtj) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/28bc62c0c4908e3138950c82f4e79f3066e6f69a/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L734)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Oh, I think I missunderstood its utility then. I actually changed it to avoid the behavior from braking when the lane change was impossible, but as we aren't going there, I can change it back to how it was. I'm gonna do some tests.
</blockquote></details>

Yeah, I just removed that part, no longer needed, going back to how it was before

**Comment by fabianoboril** [comment]
Can you update the branch? Then we can merge it :)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 4 files at r5, 2 of 3 files at r6, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/624)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
