### PR TITLE
Added support for LaneOffsetAction

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

This PR adds support for [OSC LaneOffsetAction](https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/index.html).

Added a new behaviours called ChangeActorLaneOffset to change the offset on runtime. Extended the LocalPlanner to be able to set an offset to the lateral controller ([this CARLA's PR](https://github.com/carla-simulator/carla/pull/3678))

Some important notes:
- Both the behavior and the controller might break if the offset is high enough to make the vehicle move outside the desired lane 
- Added a *get_last_lane_offset_command* to the *actor_control.py*, as if two *LaneOffsetAction* are triggered consecutively, the terminate of the first one will overwrite the initialization of the second behavior, setting it to 0, and not the desired value.

This file ([LaneOffsetActionTest.zip](https://github.com/carla-simulator/scenario_runner/files/5652014/LaneOffsetActionTest.zip)) can be used to test the new behavior. It is a modification of the *LaneChangeSimple.xosc* but changing the lane change to two LaneOffsetActions
 
**This PR will be ready when the changes to CARLA's local planner are in master (in other words, when 0.9.11 releases).** 
**EDIT: With 0.9.11, this can now be merged into the main branch**

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24
  * **CARLA version:** 0.9.10.1

### Possible Drawbacks

None, as this is just an extension of the code

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/702)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/702)* status: all files reviewed, 4 unresolved discussions (waiting on @glopezdiest)

___
*[Docs/openscenario_support.md, line 120 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVzb2EyUJ3r1SHYIX:-MQqVzb2EyUJ3r1SHYIY:b-p2v39t) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/Docs/openscenario_support.md#L120)):*
> ```Markdown
> | `ControllerAction`                                  | &#9989;            | &#9989;            | AssignControllerAction is supported, but a Python module has to be provided for the controller implementation, and in OverrideControllerValueAction all values need to be `False`. |
> | `LateralAction`<br> `LaneChangeAction`             | &#10060;             | &#9989;            | Currently all lane changes have a linear dynamicShape, the dynamicDimension is defined as the distance and are relative to the actor itself (RelativeTargetLane).                  |
> | `LateralAction`<br>`LaneOffsetAction`             | &#9989;             | &#10060;             |  Currently all type of dynamicShapes are ignored and depend on the controller. This action might not work as intended if the offset is high enough to make the vehicle exit its lane  |
> ```

Maybe mention that currently only the NPC controller supports the action.
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 50 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqUrbpAXlim62TUZ-j:-MQqUrbpAXlim62TUZ-k:b-wauxg) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/76393452bb14c50fe946eeebff346c65af2d49af/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L50)):*
> ```Python
>         Update the plan (waypoint list) of the LocalPlanner
>         """
>         self._local_planner._waypoint_buffer.clear()    # pylint: disable=protected-access
> ```

This is required, if several plans are executed after each other. Was there a reason why you removed it?
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 61 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVLfiEO6QPSfcwLz0:-MQqVLfiEO6QPSfcwLz1:b-fvnqmt) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L61)):*
> ```Python
>         Update the plan (waypoint list) of the LocalPlanner
>         """
>         self._local_planner._vehicle_controller._lat_controller._offset = self._offset   # pylint: disable=protected-access
> ```

Can someone in CARLA please add getters. Having these private accesses is not a very good style.
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 98 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVntEEVGMYTQkAOWh:-MQqVntEEVGMYTQkAOWi:b-yp7f7s) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L98)):*
> ```Python
>         if self._offset_updated:
>             self._offset_updated = False
>             self._update_offset()
> ```

Can we add something to the other controllers to either support the offset, or at least provide a message that the offset is ignored?

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/702)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @fabianoboril)

___
*[Docs/openscenario_support.md, line 120 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVzb2EyUJ3r1SHYIX:-MQr0we-5kWQRXO21bkt:bkj8ae8) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/Docs/openscenario_support.md#L120)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Maybe mention that currently only the NPC controller supports the action.
</blockquote></details>

Added support for simple vehicle controller, which should be all of the lateral controller we have
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 50 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqUrbpAXlim62TUZ-j:-MQr1HmB5tPi3jQS4goj:b-vfut5v) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/76393452bb14c50fe946eeebff346c65af2d49af/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L50)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This is required, if several plans are executed after each other. Was there a reason why you removed it?
</blockquote></details>

I removed this because this is already done when setting the global plan. If I recall correctly, the fact that we didn't clear the buffer was a bug we had at the local planner, which we fixed a while back. Most likely, we created the OSC controllers before fixing that, which is why that line was needed, but not anymore.
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 61 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVLfiEO6QPSfcwLz0:-MQr16-K8jFfb9Iszkas:by13kbg) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L61)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can someone in CARLA please add getters. Having these private accesses is not a very good style.
</blockquote></details>

Agreed, we should do that. I'll do that after this PR
___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 98 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqVntEEVGMYTQkAOWh:-MQr12F2EY622hHS3avr:bkj8ae8) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/a5483d0492b61991a1501d5dfc132daffe77eae4/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L98)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can we add something to the other controllers to either support the offset, or at least provide a message that the offset is ignored?
</blockquote></details>

Added support for simple vehicle controller, which should be all of the lateral controller we have

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/702)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[srunner/scenariomanager/actorcontrols/npc_vehicle_control.py, line 50 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/702#-MQqUrbpAXlim62TUZ-j:-MQrSXqFAfoO3oMmGW5D:bdvuii4) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/76393452bb14c50fe946eeebff346c65af2d49af/srunner/scenariomanager/actorcontrols/npc_vehicle_control.py#L50)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I removed this because this is already done when setting the global plan. If I recall correctly, the fact that we didn't clear the buffer was a bug we had at the local planner, which we fixed a while back. Most likely, we created the OSC controllers before fixing that, which is why that line was needed, but not anymore.
</blockquote></details>

Ah... Good to know. :)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/702)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
