### PR TITLE
Updated Traffic scenario 09

### PR DESCRIPTION
**Pull request by zaaramariyam**
#### Description
As per feedback, modified Traffic Scenario 09.

Fixes #  
Ego-vehicle traffic light set to green.

#### Where has this been tested?

  * **Platform(s):** 18.04
  * **Python version(s):** 2.7
  * **Unreal Engine version(s):** 4.21
  * **CARLA version:** 0.9.4

#### Possible Drawbacks
None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/97)

### CODE REVIEW

**Comment by zaaramariyam** [comment]
Working on flow of vehicles.

**Comment by nishanthjois** [comment]
1. Adversary avoiding collision should get automatically fixed once PR #117 gets merged.
2. Flow of vehicles will implement similar to PR #115.

**Comment by zaaramariyam** [comment]
There is some issue regarding avoid collision/obstacle detection in waypointfollower.

Looking into it.

**Comment by zaaramariyam** [comment]
Added avoid collision flag, and flow of adversary flag is disabled for now(due to spawning issues in waypoint follower --https://youtu.be/vCH2CsEMj-Y)

**Comment by zaaramariyam** [comment]
avoid collision flag may not work when adversary is near intersection.

**Comment by zaaramariyam** [comment]
Added avoid collision changes, adversary vehicle now doesn't crash with any other vehicle.

**Comment by zaaramariyam** [comment]
1.Rebased.
2.Added avoid collision changes, adversary vehicle now doesn't crash with any other vehicle.

**Comment by fabianoboril** [comment]
I close this PR for now. If we decide to come back to this update, we can just re-open it.

**Pull request closed without merging**
