### PR TITLE
Added Support for ParameterAction with example

### PR DESCRIPTION
**Pull request by sagar-g-v**
#### Description

Added support for Parameter action for Init

  - [x] SetAction
  - [x] ModifyAction

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8
  * **Unreal Engine version(s):** ...
  * **CARLA version:** 0.9.11

#### Possible Drawbacks
Unknown

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/728)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/728)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sagar-g-v)

___
*[srunner/tools/openscenario_parser.py, line 196 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/728#-MV_gq-k6FWZDq-oUL0U:-MV_gq-k6FWZDq-oUL0V:bq160ej) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/fe867bdd37ed2c43da648cadb484a15768e86f34/srunner/tools/openscenario_parser.py#L196)):*
> ```Python
>             if xml_tree.find("Storyboard") is not None:
>                 init_param_actions = xml_tree.find("Storyboard").find("Init").find("Actions")
>                 for global_action in init_param_actions.iter("GlobalAction"):
> ```

Can't the global_action be also used while the story is active? I.e. can't the parameter be changed while the scenario is progressing? I guess this is not covered.

**Comment by fabianoboril** [comment]
Hi,
thanks a lot for this PR. I general, I like it a lot. I only want to understand the implications a bit better. To my understanding, parameters can also be changed with ParameterActions while the scenario is active (not only during init). In this case your PR will not help, right? Can you think of a way to extend it to this more generic case?

**Comment by sagar-g-v** [comment]
Hi. I agree that the implementation is not complete. I will rethink and make it generic.

**Comment by fabianoboril** [comment]
I will close this PR for the moment. When the update is ready, please re-open the PR.

**Pull request closed without merging**
