### PR TITLE
Dev route challenge

### PR DESCRIPTION
**Pull request by felipecode**
#### Description
Adding the first version of the route evaluation to development

#### Where has this been tested?

  * **Platform(s):**  
 * **Python version(s):** 3.5
  * **Unreal Engine version(s):** ...
  * **CARLA version:** Latest Nightly Carla build (25/03/2019)

#### Possible Drawbacks
Sorry for all the commits, I was having to commit before each test.
Jose Carlos Ferrugem is my fathers computer, I forgot to setup git name properly :)

There are still several things to fix:

Weird behavior on town04 ( Scenarios are not found)
Some positions seem to be invalid.
Town03 seg faults the system
The synchronous mode still makes the server to hang when restarting the system. Probably some termination of the world object

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/114)

### CODE REVIEW

**Comment by felipecode** [comment]
___
*[srunner/scenarios/config_parser.py, line 84 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavMuem2S_H2UoQ4BJ9:-LavQVnk72WCNxDmwd24:b-rvqo12) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/scenarios/config_parser.py#L84)):*
>          yaw = float(set_attrib(node, 'yaw', 0))
> > 
> >         random_location = False
> >         if 'random_location' in node.keys():
> >             self.random_location = True
> >             random_location = True
> > 
> >         autopilot = False
> >         if 'autopilot' in node.keys():
> >             self.autopilot = True
> >             autopilot = True
> > 
> >         self.transform = carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z), carla.Rotation(yaw=yaw))
> >         self.model = set_attrib(node, 'model', 'vehicle.*')
> > 
> > 
> >         super(ActorConfiguration, self).__init__(
> >             set_attrib(node, 'model', 'vehicle.*'),
> >             carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z), carla.Rotation(yaw=yaw)),
> >             autopilot, random_location)
> > 
> > 
> > class ScenarioConfiguration(object):
> > def parse_scenario_configuration(file_name, scenario_name):   ⋯ expand 44 lines
> >             new_config.target = TargetConfiguration(target)
> > 
> >         for route in scenario.iter("route"):
> >             route_conf =RouteConfiguration()
> >             new_config.route = RouteConfiguration(route)
> >             new_config.route = route_conf.parse_xml(route)
> > 
> >         for other_actor in scenario.iter("other_actor"):
> >             new_config.other_actors.append(ActorConfiguration(other_actor))
> > ```
I think it was at some point, but I re-added it since it is quite unconvinient to have to instance an Actor Configuration from an XML node.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 267 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-Laus_Fm5KmwsrrZHWJ6:-LavSanv1g0BIOkpwMGr:br7hk0u) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L267)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Why not using self.world.wait_for_tick()?


Btw. where is this code supposed to run? In the user docker container?
</blockquote></details>

User docker container. CARLA server goes in another container.

**Comment by fabianoboril** [comment]
> _[srunner/challenge/challenge_evaluator_routes.py, line 267 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-Laus_Fm5KmwsrrZHWJ6:-LavSanv1g0BIOkpwMGr:br7hk0u) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L267)):_
> 
> Previously, fabianoboril (Fabian Oboril) wrote…
> User docker container. CARLA server goes in another container.

So there will be an obvious example on how to access world info available to the user?

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 267 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-Laus_Fm5KmwsrrZHWJ6:-LavZwaa9wIPqC1einUO:bw0n6jj) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L267)):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

User docker container. CARLA server goes in another container.
</blockquote></details>

Wait for tick is done. I have to keep ticking the server so the sensors produce their first output and things can start.

**Comment by felipecode** [comment]
___
*[srunner/challenge/autoagents/HumanAgent.py, line 145 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavKLY-4sp0_Y7VmpAR:-Lav_Pp_BdmDqZP3myX4:b-896fjx) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/autoagents/HumanAgent.py#L145)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can we remove this print statement?
</blockquote></details>

Done

**Comment by felipecode** [comment]
___
*[srunner/challenge/utils/route_configuration_parser.py, line 109 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavLrGj79xfG0XGYge_:-Lav_V006r37aJyCuiAI:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/utils/route_configuration_parser.py#L109)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Haha, excellent comment. Maybe put it next to the definition of the threshold and rephrase it a bit.

Maybe also define a constant for the angle
</blockquote></details>

Done.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 116 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LaurCHn7OEj50uE4dIv:-LaveaRJ6ksXs2KZI2Ot:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L116)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This won't work with Python2 (i.e. ROS). Please see the fixes we added to the challenge_evaluator.py

We should think about code consolidation ;-)
</blockquote></details>

Done.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 59 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauqpA4DLbDVg7pNpvG:-LavgJbh3P1YuypGO3yz:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L59)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

configuration
</blockquote></details>

Done.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 84 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-Laur45iAd2yxZqfxZhW:-Lavl-p55RTQtVzjFv5e:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L84)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Maybe run the formatting script provided in the utils folder
</blockquote></details>

Done.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 710 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauwOIg7BBxmea7PlHN:-Lavl8ZfEMxoCD6oLmwG:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L710)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

If the init fails, the del will fail. Maybe set challenge_evaluator = None outside of the try-block
</blockquote></details>

Done.

**Comment by felipecode** [comment]
___
*[srunner/challenge/utils/route_manipulation.py, line 40 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavMVOY9L2K5WAVDPkH:-LavmHYQ0RIyDbfSpXug:b-e7libp) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/utils/route_manipulation.py#L40)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Do you know Proj.4 (https://proj4.org/) and its python version pyproj? You may want to use this one here, instead of implementing your own GNSS <-> Metric conversion.
</blockquote></details>

Maybe for other PR ?

**Comment by felipecode** [comment]
___
*[srunner/scenarios/config_parser.py, line 47 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauwoCa0X1L2KDeea6Q:-LavmPf5-zjgVZSuy3xQ:btf5chf) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/scenarios/config_parser.py#L47)):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

> ```
> 
> class RouteConfiguration(object):   ⋯ expand 3 lines
>     This class provides the basic  configuration for a route
>     """
> 
>     def __init__(self, node):
>     def __init__(self, route=None):
>         if route is not None:
>             self.data = route
>         else:
>             self.data = None
> 
> 
>     def parse_xml(self, node):
>         self.data = []
> 
>         for waypoint in node.iter("waypoint"):
>             x = float(set_attrib(waypoint, 'x', 0))
>             y = float(set_attrib(waypoint, 'y', 0))
>             z = float(set_attrib(waypoint, 'z', 0))
>             c = set_attrib(waypoint, 'connection', '')
>             connection = RoadOption[c.split('.')[1]]
> 
>             self.data.append((carla.Location(x, y, z), connection))
> 
> 
> # TODO this is the same as the target they could be the same structure ? or some inherited thing
> 
> class TriggerConfigurariton(object):
> 
>     """
>     This class provides the basic  configuration for a some trigger location
>     """
> 
>     transform = None
> 
>     def __init__(self, node):
>         pos_x = float(set_attrib(node, 'x', 0))
>         pos_y = float(set_attrib(node, 'y', 0))
>         pos_z = float(set_attrib(node, 'z', 0))
> 
>         self.transform = carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z))
> 
> 
> class TargetConfiguration(object):
> 
>     """
>     def __init__(self, node):   ⋯ expand 4 lines
> 
>         self.transform = carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z))
> 
> class ActorConfigurationData(object):
>     """
>     This is a configuration base class to hold model and transform attributes
>     """
>     def __init__(self, model, transform, autopilot=False, random=False):
>         self.model = model
>         self.transform = transform
>         self.autopilot = autopilot
>         self.random_location = random
> 
> 
> class ActorConfiguration(object):
> class ActorConfiguration(ActorConfigurationData):
> 
>     """
>     This class provides the basic actor configuration for a
>     scenario:
>     - Location and rotation (transform)
>     - Model (e.g. Lincoln MKZ2017)
>     """
> 
>     transform = None
>     model = None
>     autopilot = False
>     random_location = False
> 
>     def __init__(self, node):
> 
>         pos_x = float(set_attrib(node, 'x', 0))
>         pos_y = float(set_attrib(node, 'y', 0))
>         pos_z = float(set_attrib(node, 'z', 0))
>         yaw = float(set_attrib(node, 'yaw', 0))
> 
>         random_location = False
>         if 'random_location' in node.keys():
>             self.random_location = True
>             random_location = True
> 
>         autopilot = False
>         if 'autopilot' in node.keys():
>             self.autopilot = True
>             autopilot = True
> 
>         self.transform = carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z), carla.Rotation(yaw=yaw))
>         self.model = set_attrib(node, 'model', 'vehicle.*')
> 
> 
>         super(ActorConfiguration, self).__init__(
>             set_attrib(node, 'model', 'vehicle.*'),
>             carla.Transform(carla.Location(x=pos_x, y=pos_y, z=pos_z), carla.Rotation(yaw=yaw)),
>             autopilot, random_location)
> 
> 
> class ScenarioConfiguration(object):
> def parse_scenario_configuration(file_name, scenario_name):   ⋯ expand 44 lines
>             new_config.target = TargetConfiguration(target)
> 
>         for route in scenario.iter("route"):
>             route_conf =RouteConfiguration()
>             new_config.route = RouteConfiguration(route)
>             new_config.route = route_conf.parse_xml(route)
> 
>         for other_actor in scenario.iter("other_actor"):
>             new_config.other_actors.append(ActorConfiguration(other_actor))
> ```

</blockquote></details>

removed, it was not beeing used

**Comment by felipecode** [comment]
___
*[srunner/testing/test_route_parser.py, line 6 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavNIy50Xv42G0BHJHl:-LavmWdn59KnYG3Ij37N:b-49ef55) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/testing/test_route_parser.py#L6)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Please remove everything not required
</blockquote></details>

The test is useful should I keep it in another repo ? These two tests build or parser the scenarios without actually
running them. That is useful whenever any change happens on the rest of the system or new routes/scenarios are added.

**Comment by felipecode** [comment]
___
*[srunner/testing/test_route_parser.py, line 83 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavNR1fDauKxdT-xxZk:-LavmxA8BlcHXcSQ-0MF:b663hps) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/testing/test_route_parser.py#L83)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Is this doing something meaningful? To me it looks like a first draft for a test. Maybe do not commit this at the moment?
</blockquote></details>

See my other comment. The test is missing assertions but it should run without crashing at least.

**Comment by felipecode** [comment]
___
*[srunner/testing/test_scenario_building.py, line 75 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LavNcaoCaYMV_Lpc9oG:-LavnLRC75DhsvdBjME6:b24sit9) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/testing/test_scenario_building.py#L75)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Please cleanup comments. Is it required to check this file in? See my comment for the other test.
</blockquote></details>

See my comment

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 87 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauvAEi1pY9jn98zE60:-LavnPk4ANZYqbGq-NG5:bahg55v) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L87)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This class is a collection of everything. Maybe split into several classes, e.g. for result evaluation, sensor stuff, scenario loading things, etc.
</blockquote></details>

This will take time... I will take to german about that. Maybe anotheer PR ?

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 366 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauvlXC9LsDmHFO7Tbr:-LavnnJs0vJokM78WpJY:b-h56rbx) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L366)):*
> I think this is some general discussion, not part of the PR. This parameters need to be tested and discussed separately.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 368 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-Lautq84DXt3wJuqwRa-:-LavnaRRAkOmuMUCl61X:bybxwf9) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L368)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

I think the penalty for wrong_way is a bit high. The ControlLoss scenario will most likely lead to this penalty, and if you face this scenario twice, the overall penalty is already comparable to running a red light, which is far worse. So I suggest to reduce this value.

Btw: Is this going to be public (e.g. on the Challenge website?)?
</blockquote></details>

I think this is some general discussion, not part of the PR. This parameters need to be tested and discussed separately.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 431 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauuHkuE79L9b_tbxEc:-Lavnqh76nlFpQE-aPDt:bybxwf9) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L431)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Here it does not matter how much time I require to reach the target. Imagine I go super slowly, which may trigger a lot of scenario timeouts (good?) and I have far more time to react on obstacles. I would somehow try to bring in the time...
</blockquote></details>

I think this is some general discussion, not part of the PR. This parameters need to be tested and discussed separately.

**Comment by felipecode** [comment]
___
*[srunner/challenge/challenge_evaluator_routes.py, line 637 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/114#-LauxBKV63-B8fm3aOU-:-LavoGoOEN9d6LaX8fGE:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7b90d9ce44017242d429e1e6f35f0312e6be351c/srunner/challenge/challenge_evaluator_routes.py#L637)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

You are not using the ScenarioManager here, it seems? Then you can remove it from the class
</blockquote></details>

Done.

**Pull request merged**
