### PR TITLE
Added check to ensure names in OSC are unique

### PR DESCRIPTION
**Pull request by fabianoboril**
The check provides a Warning, if the name of a story, act, maneuvergroup or maneuver
(e.g. story_name->act_name->maneuvergroup_name) appears more than once.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)

### CODE REVIEW

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @fabianoboril and @glopezdiest)

___
*[srunner/scenarios/open_scenario.py, line 33 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/659#-MJaI0qg4zaPpfr4RGSz:-MJaI0qg4zaPpfr4RGT-:b2jq2s5) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1ca80ae2d07b41f9f4da7d608054417e4d967ab1/srunner/scenarios/open_scenario.py#L33)):*
> ```
> dublicated
> ```
duplicated

**Comment by glopezdiest** [comment]
Checking the code, the _oneshot_ function swapped hasn't been done at the *openscenario_parser.py -> converter_maneuver_to_atomic*. Is this the intended behavior?


Additionally, I've tried testing this but there seems to be a problem with the EnvironmentAction, not being properly read. The first conditional seems to always trigger the return, always using the default parameters,
image

**Review by fabianoboril — COMMENTED** [review]
Hm... let me rework this part.

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659#-:-MJgSW0G6vjHs_ASPvHm:b50hevw)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

**Review by glopezdiest — APPROVED** [review]
As discusses via Discord, this EnvironmentAction error can be looked at at another PR, I'm approving this one

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659#-:-MJzvPCe-VU7Wmv8AKAk:b-1av73j)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

**Review by fabianoboril — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[srunner/scenarios/open_scenario.py, line 33 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/659#-MJaI0qg4zaPpfr4RGSz:-MK0idoT5IfIRxoJPdTn:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1ca80ae2d07b41f9f4da7d608054417e4d967ab1/srunner/scenarios/open_scenario.py#L33)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

> ```
> dublicated
> ```
duplicated
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

**Review by glopezdiest — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/659)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
