### PR TITLE
Traffic Scenario 09

### PR DESCRIPTION
**Pull request by zaaramariyam**
#### Description
Implementation of Traffic Scenario 09.
Added multiple locations.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ...18.04
  * **Python version(s):** ...2.7
  * **Unreal Engine version(s):** ...4.21
  * **CARLA version:** ...0.9.4

#### Possible Drawbacks
If hero actor takes right turn first, there might be chances of collision.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/82)

### CODE REVIEW

**Comment by zaaramariyam** [comment]
If hero actor takes right turn first, there might be chances of collision.

**Comment by zaaramariyam** [comment]
PR is ready for review.

**Comment by zaaramariyam** [comment]
> > Reviewed 1 of 11 files at r3, 5 of 6 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/82)_ status: all files reviewed, 1 unresolved discussion (waiting on @nishanthjois and @zaaramariyam)
> 
> _[srunner/scenarios/signalized_junction_right_turn.py, line 34 at r4](https://reviewable.io/reviews/carla-simulator/scenario_runner/82#-LaLFZ3kEXzUkRcRtGIO:-LaLFZ3kEXzUkRcRtGIP:b-7wb218) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/c9c76c5f3a703dd4797527ade705aa81ee246128/srunner/scenarios/signalized_junction_right_turn.py#L34)):_
> 
> > ```python
> >     timeout = 80  # Timeout of scenario in seconds
> > 
> >     def __init__(self, world, ego_vehicle, config, randomize=False, debug_mode=False):
> > ```
> 
> Please update to the recent changes in development

Okay.

**Comment by pravinblaze** [comment]
Re-based

**Pull request merged**
