### PR TITLE
OpenSCENARIO 2.0 supported 

### PR DESCRIPTION
**Pull request by synkrotron**
#### Description

We supported OpenSCENARIO 2.0 standard in this feature.
We implemented a compilation system to compile and execute osc2's code, and implemented part of the domain model.
We wrote some scenario files with .osc file extensions and each passed the test.
Please read README_OpenSCENARIO_2.0.md for more details.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8.10
  * **Unreal Engine version(s):** UE4
  * **CARLA version:** 0.9.13

#### Possible Drawbacks

The support for the domain model is not complete, but some simple scenarios can already be implemented, such as the. osc file example in the example folder.

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1015)

### CODE REVIEW

**Comment by synkrotron** [comment]
@glopezdiest We have re-created the PR for openscenario 2.0 support, please ignore previous one #990

**Comment by germanros1987** [comment]
@joel-mb could you review this, please?

**Comment by synkrotron** [comment]
We have updated the code to address the static code check.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 166 of 242 files at r1, 14 of 33 files at r2, 2 of 3 files at r3, 68 of 68 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Pull request merged**
