### PR TITLE
Added basic OSC's FollowTrajectoryAction support

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

This PR adds basic support for the [OSC's FollowTrajectoryAction](https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/index.html). This actions includes:
- 3 types of trajectory shapes (_Polyline_, _Clothoid_ and _Nurbs_). Only Polylines are supported
- Temporal constraints to the trajectory. Currently unsupported
- 2 types of trajectory following mode (_position_, hard following of the route, and _follow_, up to the controller). Only _follow_ mode is supported.

[Here](https://github.com/carla-simulator/scenario_runner/files/6310124/FollowTrajectoryTest.zip) is an example to test the FollowTrajectoryAction.

EDIT: Thanks to [jackokaiser's PR](https://github.com/carla-simulator/scenario_runner/pull/866), time constraints for trajectories are also supported

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** 0.9.11 (current _dev_)

### Possible Drawbacks

None, as this is just an addition

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/751)

### CODE REVIEW

**Comment by simon-jarvers** [comment]
Hi @glopezdiest,
this PR looks really promising to me! Do you know whether it will be merged anytime soon?

I am working on a way to visualize multiple FollowTrajectoryActions with given sequences of time and positions. (example trajectory attached) However as far as I could tell in the current state, only the positions are used to change the actors waypoints; the time attribute of the vertices are neglected. Instead, the prior event "AdversaryAccelerates" sets a fixed target speed to get the actor moving.
I tried to utilize the given positions and timestamps to calculate the desired velocities but didn't find a way to change the velocity dynamically. As I am quite new to CARLA, I would be appreciate any ideas or input how to tackle this task. Thanks a lot in advance!

Also please let me know whether this question is misplaced here. I would be glad to open a separate issue to not spam this PR with unrelated content.

[example_trajectory.txt](https://github.com/carla-simulator/scenario_runner/files/8197842/example_trajectory.txt)

**Review by joel-mb — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/751)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Comment by jch458** [comment]
Dear all, thank you for the excellent work. I am trying to generate OSC files with FollowTrajectoryAction. I tried CARLA and SR 0.9.12 and 0.9.13, which seem not working. Should I try the master branches for both CARLA and SR to get this new feature?

Many thanks!

**Comment by jackokaiser** [comment]
Hi @jch458

Personally I'm using CARLA release 0.9.13 and pulled the master branch for `scenario_runner`.

**Pull request merged**
