### PR TITLE
Update osc2_scenario_configuration.py

### PR DESCRIPTION
**Pull request by Ylmdrin**
#### Description

Updated file srunner/scenarioconfigs/osc2_scenario_configuration.py to fix the following error, obtained when running scenario_runner.py with the --openscenario2 parameter and any of the OpenScenario v2 example scenarios in srunner/examples :

`Preparing scenario: srunner/examples/*.osc`
`The scenario cannot be loaded`
`Traceback (most recent call last):`
`  File "scenario_runner.py", line 400, in _load_and_run_scenario`
`    scenario = OSC2Scenario(world=self.world,`
`  File "scenario_runner/srunner/scenarios/osc2_scenario.py", line 466, in __init__`
`    super(OSC2Scenario, self).__init__(`
`  File "/scenario_runner/srunner/scenarios/basic_scenario.py", line 50, in __init__`
`    self.route_mode = bool(config.route)`
`AttributeError: 'OSC2ScenarioConfiguration' object has no attribute 'route'`
`'OSC2ScenarioConfiguration' object has no attribute 'route'`
`No more scenarios .... Exiting`

Added a call to the __init__ method of the super class to OSC2ScenarioConfiguration.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04.6 LTS
  * **Python version(s):** Python 3.8.18
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** 0.9.15

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1040)

### CODE REVIEW

**Comment by germanros1987** [comment]
@glopezdiest please review.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1040)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ylmdrin)

**Comment by glopezdiest** [comment]
Agreed, with the introduction of the Leaderboard 2.0, the `route_mode` was added, which broke OSC scenarios

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1040)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ylmdrin)

**Comment by hsiang-lee** [comment]
https://osc2studio.online

**Pull request merged**
