### PR TITLE
JSON report feature

### PR DESCRIPTION
**Pull request by dsche**
#### Description

This series of commits adds an additional command-line option to produce a JSON report file. In contrast to the JUnit XML, the JSON report captures in a machine-readable fashion the individual test criteria for further automated analysis.

Technically, this is implemented analogously to the JUnit XML output, with the same file name pattern.

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.7.6
  * **Unreal Engine version(s):** ...
  * **CARLA version:** 0.9.10

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @dsche)

___
*[scenario_runner.py, line 255 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/651#-MIrweo3-Y15KOCa1iHj:-MIrweo3-Y15KOCa1iHk:bs632rs) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/56bc4111ec1756d81f732158cc807f4616b941cf/scenario_runner.py#L255)):*
> ```Python
>             junit_filename = config_name + current_time + ".xml"
>         if self._args.json:
>             json_filename = res_dir + config_name + current_time + ".json"
> ```

Maybe add this also to the junit part.

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)* status: all files reviewed, 2 unresolved discussions (waiting on @dsche)

___
*[srunner/scenariomanager/carla_data_provider.py, line 223 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/651#-MIrxQ5Z7vqAMoOGA7_p:-MIrxQ5Z7vqAMoOGA7_q:b-cmjrv2) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/56bc4111ec1756d81f732158cc807f4616b941cf/srunner/scenariomanager/carla_data_provider.py#L223)):*
> ```Python
>         """
>         rgx = re.compile('.+?(?:(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])|$)')
>         def name(x): return ' '.join(m.group(0) for m in rgx.finditer(x))
> ```

Maybe better exclude this change from this PR (has nothing to do with json writer)

**Comment by fabianoboril** [comment]
Hi,
thank you very much for this PR and this nice addition. We have one suggestion for improving the PR.

**Comment by dsche** [comment]
Thanks for the review! However, on a second thought I am not sure if you need a parallel mechanism for setting an output directory. Would you mind if I remove that here and open another PR for that?

**Comment by jimmyw404** [comment]
Tested your branch, works great! Thanks for adding this, fills a need we have!

**Review by dsche — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @dsche and @fabianoboril)

___
*[srunner/scenariomanager/carla_data_provider.py, line 223 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/651#-MIrxQ5Z7vqAMoOGA7_p:-MJ6UKy448_Y3NTtOl9D:bb6un1j) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/56bc4111ec1756d81f732158cc807f4616b941cf/srunner/scenariomanager/carla_data_provider.py#L223)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Maybe better exclude this change from this PR (has nothing to do with json writer)
</blockquote></details>

Done

**Review by dsche — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @fabianoboril)

___
*[scenario_runner.py, line 255 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/651#-MIrweo3-Y15KOCa1iHj:-MJ6UhPO9kitX46-N3ie:b-43e94l) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/56bc4111ec1756d81f732158cc807f4616b941cf/scenario_runner.py#L255)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Maybe add this also to the junit part.
</blockquote></details>

I think I'd like to move this into a different PR altogether if you would not mind. The RESULTS_DIR environment variable adds a different source of truth for the output directory, which might or might not be needed (and is undocumented right now).

**Comment by fabianoboril** [comment]
I fixed an issue breaking Python2 compatibility in result_writer. If you are fine with this change, we can merge this PR.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/651)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by dsche** [comment]
Thanks! I am fine with that :-)

**Pull request merged**
