### PR TITLE
Added new metrics module

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

**Added a metrics module to SR**, which allows the user to implement their own metrics. This module will give the user all the information about the simulation (using the criteria and the CARLA recorder), so that they can implement any metrics they desire.

The **recorder at *scenario_runner.py*** has been modified. **It now requires a path** (relative to SCENARIO_RUNNER_ROOT), where the CARLA recorder will be saved. It **also saves the criteria**, dumping all the JSON serializable attributes into a .json file.

image

The main file of the metrics module is **metrics_manager.py**. It functions similar to *scenario_runner.py*, and it's used to pass all the arguments needed. These arguments
   1. **--metric:** path to a .py file with the metric created by the user
   2. **--log:** path to the CARLA recorder file.
   3. **--criteria** (optional): path to a .json file with the criteria.

In order to create the metric, a **basic_metric.py** has been created. This **works very similar to BasicScenario**, where all the user-made metrics have to inherit from this class. This allows the user to create several metrics while quickly choosing which one to use. In order to make it work, the user only has to overload the *_create_metrics* function. If the *__init__* is overloaded, make sure to call the *BasicMetric* one too.

Three metrics have been created to exemplify how to acces the different information (town_map, recorder and criteria) :
- **distance_between_vehicles.py**: uses the recorder to calculate and the distances between two vehicles. Data taken from FollowLeadingVehicle scenario
- **distance_to_lane_center.py**: uses the recorder as well as the map API to get the deviation from the center of the lane with respect to time. Data taken from ControlLoss scenario
- **criteria_filter.py**: saves the most important attributes of the criteria to a json file. Data taken from RouteScenario

Two other files have been created, to support the metrics module.
- **metrics_parser.py**: which parses the string given by the CARLA recorder into a readable dictionary.
- **metrics_log.py**: class used to access this parsed information in an easy way

**Drawbacks**:

Due to the metrics being calculated at the end of the simulation, no instances of actors can be created. This results in some **some information about the actors is missing**. 

Additionally, as of right now the **output of the metrics is left completely to the user**, but it might be good to add some functions to have a standard, which we can use to do unittests / debug.

**How to run the metrics:**

1. Run a scenario with the _record_ argument (which again, now needs a path, relative to SCENARIO_RUNNER_ROOT). This will create a *.log* and *.json* files in that folder

`python3 scenario_runner.py --scenario FollowLeadingVehicle_1 --record srunner/metrics/data`

2. Run *metrics_manager.py*. We'll be using the *distance_between_two_vehicles.py* example metric, which doesn't need the criteria argument:

`python3 metrics_manager.py --metric srunner/metrics/distance_between_two_vehicles.py --log srunner/metrics/data/FollowLeadingVehicle_1.log`

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.24
  * **CARLA version:** 0.9.9.4

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)

### CODE REVIEW

**Comment by glopezdiest** [comment]
I'm currently doing these two metrics, to see how the metrics system handles them
- Near collisions (given a threshold). Detect only a walker.
- Traffic light counting (speed of the vehicle, state of the traffic light...).

**Comment by glopezdiest** [comment]
Adding @sergi-e to review the Docs

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @fabianoboril and @sergi-e)

___
*[metrics_manager.py, line 64 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MAzAFE9At09k9Nretew:-MG3RhbMEtwrqhvnuRq_:b-qe0bfj) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/b11fe156fc08ed35f4dac8402c622a433861165c/metrics_manager.py#L64)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

I still wonder, if you can combine several metrics now, to enable re-use instead of copy&paste...
</blockquote></details>

No, that still isn't the case. Regarding how metrics are run, they do so the same as scenarios. To combine metrics implies a very similar process as to combine multiple scenarios, which is currently impossible
___
*[srunner/metrics/tools/metrics_log.py, line 17 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MEcGkNxDqhp4mwyA8Wx:-MG3CZfE-dh-DfT_62Lm:b-e0in6k) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/2b44bae2b32284bf7a13678f193f9a90ab3951a4/srunner/metrics/tools/metrics_log.py#L17)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Is this a standard python library, or an additional pip package? If the latter, it should be added to the requirements.txt
</blockquote></details>

As far as I know, it is a standard library.
___
*[srunner/metrics/tools/metrics_log.py, line 239 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MEcH-L68HVwMQ3l6JSL:-MG3CZI6859GpLenR4wM:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/2b44bae2b32284bf7a13678f193f9a90ab3951a4/srunner/metrics/tools/metrics_log.py#L239)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Please remove trailing whitespaces --> Check with the codeformat script in utilities
</blockquote></details>

Done.

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: all files reviewed, 3 unresolved discussions (waiting on @fabianoboril, @glopezdiest, and @sergi-e)

___
*[srunner/metrics/examples/distance_between_vehicles.py, line 18 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MGCW5BUBhGq0oMzloLv:-MGCW5BV4YJAinhqmGQ3:b-noog5k) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1c601879a8b50fe6c37f0be2aa6b9b2f214b2106/srunner/metrics/examples/distance_between_vehicles.py#L18)):*
> ```Python
> 
> import math
> # import json
> ```

Remove if not required
___
*[srunner/metrics/tools/metrics_log.py, line 159 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MGCVxNr9hIKHyGbAuB5:-MGCVxNs3nYTIPSHMHuW:bu80y92) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1c601879a8b50fe6c37f0be2aa6b9b2f214b2106/srunner/metrics/tools/metrics_log.py#L159)):*
> ```Python
>             return None
> 
>         return None
> ```

Is this change intended? If it always returns none, what is the sense behind it?

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @fabianoboril and @sergi-e)

___
*[srunner/metrics/examples/distance_between_vehicles.py, line 18 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MGCW5BUBhGq0oMzloLv:-MGCeyaGAkZx6UFeMXbb:bwoglsm) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1c601879a8b50fe6c37f0be2aa6b9b2f214b2106/srunner/metrics/examples/distance_between_vehicles.py#L18)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Remove if not required
</blockquote></details>

My idea was to show two different ways of exporting the criteria information, being the json one commented out. At the end, as the other examples already use the json format, I've decided to remove it
___
*[srunner/metrics/tools/metrics_log.py, line 159 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/563#-MGCVxNr9hIKHyGbAuB5:-MGCcxQC3IaOuNPYvW2U:bn0siyz) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/1c601879a8b50fe6c37f0be2aa6b9b2f214b2106/srunner/metrics/tools/metrics_log.py#L159)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Is this change intended? If it always returns none, what is the sense behind it?
</blockquote></details>

It returns the trigger volume. If the actor hasn't or the actor doesn't exist, it then returns None

**Review by fabianoboril — APPROVED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril and @sergi-e)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril and @sergi-e)

**Review by sergi-e — APPROVED** [review]
> Reviewed 3 of 5 files at r9, 11 of 11 files at r10, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

**Review by fabianoboril — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/563)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by SiNa-Dehbari** [comment]
Hi all,

I wana record scenario and evaluate the data by `--metric`  feature.
I can run the pre-defined example `DistanceBetweenVehicles.log` but cannot create new one.
I followed these to lines of code:
```
python scenario_runner.py --scenario FollowLeadingVehicle_1 --record srunner/metrics/data

python metrics_manager.py --metric srunner/metrics/distance_between_two_vehicles.py --log srunner/metrics/data/FollowLeadingVehicle_1.log
```

but I get this error. 

```
Traceback (most recent call last):
  File "metrics_manager.py", line 154, in <module>
    sys.exit(main())
  File "metrics_manager.py", line 151, in main
    MetricsManager(args)
  File "metrics_manager.py", line 54, in __init__
    log = MetricsLog(recorder_str)
  File "D:\Software\Engineering\Carla\scenario_runner-0.9.11\srunner\metrics\tools\metrics_log.py", line 31, in __init__
    self._simulation, self._actors, self._frames = parser.parse_recorder_info()
  File "D:\Software\Engineering\Carla\scenario_runner-0.9.11\srunner\metrics\tools\metrics_parser.py", line 510, in parse_recorder_info
    bbox = parse_bounding_box(elements)
  File "D:\Software\Engineering\Carla\scenario_runner-0.9.11\srunner\metrics\tools\metrics_parser.py", line 186, in parse_bounding_box
    float(info[3][1:-1])/100,
ValueError: could not convert string to float: '-nan(ind)'
```

I also tried the Openscenario method for recording data, but the output was the same.

Could you please let me know how can I solve it?

Thank you in advance.

**Comment by SiNa-Dehbari** [comment]
Hello everybody,

still I'm struggling with the previous problem?
I really want to know that, is it my problem? or SR itself.

Thank you.

**Pull request merged**
