### PR TITLE
Removed CARLA example dependencies

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

The manual control script has been modified.
- It no longer depends on the CARLA version, removing dependencies from the CARLA examples.
- It has also been simplified, removing all world functionalities such as changing weather, map layer, non camera sensors . This avoids confusing the users about its functionality, which is just as an agent for the scenarios.

### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** 0.9.12

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)* status: all files reviewed, 2 unresolved discussions (waiting on @fabianoboril and @glopezdiest)

___
*[manual_control.py, line 133 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/825#-MmGycRzBC4VW4J84Ydd:-MnzUsh646ObB6hTqAGU:b32wtd) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/af50f5ee6c37375e46907ec940f278b166d51fa4/manual_control.py#L133)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I do remember that we have that idea, but in reality, I don't think it is a good one. First, we are making dependent on the examples folder, which is weird. Also, for SR the manual control should just be an agent to move the ego but for CARLA, it is an script to show how you can change weather, load/unload map sublevels... which don't really work with SR and only confuse users.

Therefore, I think it is better to just have a simplified version and don't try to add the new features.

</blockquote></details>

ok
___
*[manual_control.py, line 232 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/825#-MmGyNT4BhHb6iP40Pk7:-MnzWPYW8RXxRb08lvJQ:brkdxxx) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/0832793a1b2895d2dc3699aa9d9a456daac9aad1/manual_control.py#L232)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Which flags are you referring too?
</blockquote></details>

Those that are deleted below (role name), also sync? Maybe also seed?

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)* status: all files reviewed, 2 unresolved discussions (waiting on @fabianoboril)

___
*[manual_control.py, line 232 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/825#-MmGyNT4BhHb6iP40Pk7:-Mo2XKYd6G2hxf1UIgeh:b33k60z) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/0832793a1b2895d2dc3699aa9d9a456daac9aad1/manual_control.py#L232)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Those that are deleted below (role name), also sync? Maybe also seed?
</blockquote></details>

I don't think they fit / they might be misleading.
As the manual control is gonna run in tandem with SR, does -*--sync* make sense? should SR be the one ticking? 
*--seed* is also missleading and we aren't using it (current CARLA manual control has no seed, neither does SR's one utilize it).
I'll readd rolename, I removed that by mistake.

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @fabianoboril)

___
*[manual_control.py, line 232 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/825#-MmGyNT4BhHb6iP40Pk7:-Mo9DAiTDMlpofcx90wJ:b-vs23g8) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/0832793a1b2895d2dc3699aa9d9a456daac9aad1/manual_control.py#L232)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I don't think they fit / they might be misleading.
As the manual control is gonna run in tandem with SR, does -*--sync* make sense? should SR be the one ticking? 
*--seed* is also missleading and we aren't using it (current CARLA manual control has no seed, neither does SR's one utilize it).
I'll readd rolename, I removed that by mistake.

</blockquote></details>

Readded the rolename

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Pull request merged**
