### PR TITLE
Generalization of Traffic Scenario 04

### PR DESCRIPTION
**Pull request by akki6843**
#### Description

Generalization of Traffic scenario 04:
Other actors are spawning with respect to the location of ego vehicle's location.

Code has been checked against pep8 and pylint.   

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Linux
  * **Python version(s):**  2.7
  * **CARLA version:** 0.9.4

#### Possible Drawbacks
* Due to lane width issue in town 03
* Possible spawning issue in some locations in Town05

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/74)

### CODE REVIEW

**Comment by fabianoboril** [comment]
Any updates?

**Comment by akki6843** [comment]
> Any updates?

We have prepared a scenario helper file and have moved the actor spawning login into it.
Now rebase is going on with new changes of wait behaviour.

**Comment by akki6843** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/74)_ status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @akki6843 and @fabianoboril)
> 
> _[scenario_runner.py, line 138 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/74#-La180QQDXRj0IzIPxE0:-La180QQDXRj0IzIPxE1:botnr8e) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/b0f33ff05bb915b00cf668cc74689e1b6a23dcab/scenario_runner.py#L138)):_
> 
> > ```python
> >     def prepare_ego_vehicle(self, config):
> >         """
> > <<<<<<< HEAD
> > ```
> 
> Please properly merge your changes.

Solved merge conflicts.
Done

**Comment by akki6843** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/74)_ status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @akki6843, @fabianoboril, and @odunkel)
> 
> _[scenario_runner.py, line 138 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/74#-La180QQDXRj0IzIPxE0:-La8bu5tChv5bwSVGJSx:bytkg6n) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/b0f33ff05bb915b00cf668cc74689e1b6a23dcab/scenario_runner.py#L138)):_
> 
> > We have prepared a scenario helper file and have moved the actor spawning login into it.
> > Now rebase is going on with new changes of wait behaviour.
> 
> Quoted 14 lines of code…

Fixed
extremely sorry for this one

**Comment by akki6843** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/74)_ status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @akki6843, @fabianoboril, and @odunkel)
> 
> _[scenario_runner.py, line 242 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/74#-La8c5us7cwNU75IPtli:-La8c5us7cwNU75IPtlj:b-bvfomb) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/b0f33ff05bb915b00cf668cc74689e1b6a23dcab/scenario_runner.py#L242)):_
> 
> > ```python
> >                     self.prepare_actors(config, scenario_class)
> > >>>>>>> changed required scenario runner.
> >                     scenario = scenario_class(self.world,
> > ```
> 
> another merge conflict residual. Please fix it.

Done

**Pull request merged**
