### PR TITLE
Traffic Scenario 03

### PR DESCRIPTION
**Pull request by mohit-awana**
* Added Region based Criteria Test instead to Drive Distance criteria
* Removed Keep lane criteria for change lane without penalty
* Reduced global timeout 

#### Where has this been tested?

  * **Platform(s):** 18.04
  * **Python version(s):** 2.7
  * **Unreal Engine version(s):** ...
  * **CARLA version:** ... 0.9.2

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/21)

### CODE REVIEW

**Comment by fabianoboril** [comment]
Hi,
depending on our release strategy, we can also address my comments after the release.
@germanros1987 : Any opinion?

**Comment by fabianoboril** [comment]
> Previously, mohit-awana (Mohit Awana) wrote…
> It is working for all the locations in current towns. I will generalize after the release.

ok

**Comment by fabianoboril** [comment]
Any updates on this one?

**Comment by nishanthjois** [comment]
@fabianoboril/@germanros1987: if possible can you please review this?

**Comment by germanros1987** [comment]
Re-submit when ready

**Pull request closed without merging**
