### PR TITLE
Add Pedestrian crossing

### PR DESCRIPTION
**Pull request by TayYim**
#### Description

Add Pedestrian Crossing scenario.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** leaderboard-2.0 branch

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)

### CODE REVIEW

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenarios/object_crash_vehicle.py` line 413 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N2Rdiw_6y8vex1FI1X1:-N2Rdiw_6y8vex1FI1X2:b-nbcn4d) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/be8c167cf03754bb9b4715b2a24b7f50b7536e19/srunner/scenarios/object_crash_vehicle.py#L413)):*
> ```Python
>             spawn_transforms.append(self._get_sidewalk_transform(
>                 sidewalk_waypoint, {"yaw": 270, "z": 1.5, "k": 2}))
>             spawn_transforms.append(self._get_sidewalk_transform(
> ```

Parametrize this in the initialization, in the same way the `adversary_speed_list`



_Code quote:_
```Python
            spawn_transforms.append(self._get_sidewalk_transform(
                sidewalk_waypoint, {"yaw": 270, "z": 1.0, "k": 1}))
            spawn_transforms.append(self._get_sidewalk_transform(
                sidewalk_waypoint, {"yaw": 270, "z": 1.5, "k": 2}))
            spawn_transforms.append(self._get_sidewalk_transform(
                sidewalk_waypoint, {"yaw": 270, "z": 2.0, "k": 2}))
            spawn_transforms.append(self._get_sidewalk_transform(
                sidewalk_waypoint, {"yaw": 270, "z": 2.5, "k": 2}))
```

**Review by TayYim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[`srunner/scenarios/object_crash_vehicle.py` line 413 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N2Rdiw_6y8vex1FI1X1:-N2Tqht61AS69gJdL6KB:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/be8c167cf03754bb9b4715b2a24b7f50b7536e19/srunner/scenarios/object_crash_vehicle.py#L413)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Parametrize this in the initialization, in the same way the `adversary_speed_list`
</blockquote></details>

Done.

**Review by TayYim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenariomanager/scenarioatomics/atomic_behaviors.py` line 3509 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47HmaHEsnY1Hw_nlTs:-N4AFth_CAn3WDygmyJz:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L3509)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Make this default to None, as the CDP seed is goind to be the main usage 
</blockquote></details>

Done.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_behaviors.py` line 3509 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47O2oIEoUMgTlSDlAy:-N4AGdhj-kRid4gQ7CnP:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L3509)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

sink = 1 doesn't seem to be close enough to remove the walkers. Probably due to the navigation module rerouting them. A sink distance of 2 seems to do the trick, so adjust the default value (and probably add a warning at the docs too)
</blockquote></details>

Done.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_behaviors.py` line 3521 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47OS--8rNSCWgWqyvM:-N4AGmtt50bNUEmu9Ljy:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L3521)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`srunner/scenarios/pedestrian_crossing.py` line 60 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47Oow-1PSq8Kg-L3bQ:-N4AXptbDuDXc7YMFOoh:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenarios/pedestrian_crossing.py#L60)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This doesn't seem to need the yaw. I recommend changing it so that only the location is parsed (and needed by the config file)
</blockquote></details>

Done.
___
*[`srunner/scenarios/pedestrian_crossing.py` line 69 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47P8rr6_PYkaF-eibQ:-N4AXp32-wXlzL4bWQ9p:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenarios/pedestrian_crossing.py#L69)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Same here, only the location is used, right?
</blockquote></details>

Done.
___
*[`srunner/scenarios/pedestrian_crossing.py` line 86 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47PHUxDGRIHmi0aOeJ:-N4AYmlfAh2CK5W8uhBA:b-t1xhkz) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenarios/pedestrian_crossing.py#L86)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I'd recommend against this. Always use the CDP random seed, as using a specific one will make all scenraios part of the route copies of one another
</blockquote></details>

Removed this part.
The case is that the scenario generated based on the CDP random seed may not be good, so I want to specify another random seed. If it will also affect other scenarios, it's not a good approach. Removed.
___
*[`srunner/scenarios/pedestrian_crossing.py` line 115 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47PdJZ7I09TbotiGRZ:-N4BVJTd-VvlMgV7u1se:b4ezhjl) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenarios/pedestrian_crossing.py#L115)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This combination is weird. Right now, the scenario will keep creating pedestrians during 60 seconds and then, stop after the ego has driven a certain distance. Better to make the DriveDistance part of the parallel behavior too such that the DriveDistance is the main beahvior that stops the pedestrian flow (as driven distance = the ego has passed the pedetrian flow). A *WaitEndIntersection* could also be used, as crosswalks will always be at the entry of a junction
</blockquote></details>

Done. Use WaitEndIntersection.

**Review by TayYim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[`srunner/scenarios/pedestrian_crossing.py` line 113 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N47QQsDBfv94OFLO_M8:-N4WFEt_-Y6SsHfYELDX:bfezzqa) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/e2bc7d8508ad932a159ba7153048ccbe10573aa2/srunner/scenarios/pedestrian_crossing.py#L113)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This might not be enough as having no initial pedestrians at the crosswalk might allow the ego to drive through without having to stop. To avoid that, it'll require a careful set of trigger point and pedestrian flow source location, which is always tricky.

Try adding an initial pedestrian (or group of) at the crosswalk, see if that forces the ego to break? Not sure how that'll work though
</blockquote></details>

Add an atomic behavior called AIWalkerBehavior.
In this scenario, the user needs to specify init_walker_start and init_walker_end. A walker will go crossing the road at the beginning of the scenario.

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenarios/pedestrian_crossing.py` line 56 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N4XgwPMB-LZ2CH_sNIG:-N4XgwPMB-LZ2CH_sNIH:bbsbvq9) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/0c4ab5743778062b02998cc5bbc061fbe7200715/srunner/scenarios/pedestrian_crossing.py#L56)):*
> ```Python
>             self._trigger_location)
> 
>         self._init_walker_start = convert_dict_to_location(
> ```

Maybe use the waypoint API to detect crosswalks by checking the start of a junction? Although I'm not sure how reliable it is



_Code quote:_
```Python
        self._init_walker_start = convert_dict_to_location(
            config.other_parameters['init_walker_start'])
```
___
*[`srunner/scenarios/pedestrian_crossing.py` line 59 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/895#-N4Xgfd_ER8XwtXDdERk:-N4Xgfd_ER8XwtXDdERl:b-8mscj0) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/0c4ab5743778062b02998cc5bbc061fbe7200715/srunner/scenarios/pedestrian_crossing.py#L59)):*
> ```Python
>             config.other_parameters['init_walker_start'])
>         self._init_walker_end = convert_dict_to_location(
>             config.other_parameters['init_walker_end'])
> ```

Not really needed, just use the end walker flow 1



_Code quote:_
```Python
        self._init_walker_end = convert_dict_to_location(
            config.other_parameters['init_walker_end'])
```

**Review by glopezdiest — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/895)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TayYim)

**Pull request merged**
