### PR TITLE
Obstacle evasion OpenSCENARIO

### PR DESCRIPTION
**Pull request by dsche**
This scenario is meant to test agents for (static) obstacle evasion capability. It consists of some containers placed along the road that should be evaded.

#### Description

This PR adds an example OpenSCENARIO scenario where the agent has to evade some (static) containers.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.7.6
  * **Unreal Engine version(s):** N/A
  * **CARLA version:** 0.9.10

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/671)

### CODE REVIEW

**Comment by glopezdiest** [comment]
Hey @dsche, thanks for the PR and sorry for the delay. From my side, I don't see any problems in adding a new example to our repository. I'll take an in-depth look to see if I can find any problem with it and report back.

@fabianoboril Do you think this example would fit in our current repertoire of examples?

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Comment by fabianoboril** [comment]
Hi,
thank you for the contribution. @glopezdiest From my side we can merge it 👍

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/671)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
