### PR TITLE
Added compatibility with CARLA 0.9.12

### PR DESCRIPTION
**Pull request by glopezdiest**
### Description

This PR updates SR to be compatible with CARLA 0.9.12, but looses compatibility with CARLA 0.9.11. Changes:
- Some blueprint names have been changed. Full list below
```
vehicle.bmw.isetta -> vehicle.micro.microlino
vehicle.dodge_charger.police -> vehicle.dodge.charger_police
vehicle.mercedes-benz.coupe -> vehicle.mercedes.coupe
vehicle.mini.cooperst -> vehicle.mini.cooper_s
vehicle.lincoln.mkz2017 -> vehicle.lincoln.mkz_2017
vehicle.mustang.mustang -> vehicle.ford.mustang
vehicle.lincoln2020.mkz2020 -> vehicle.lincoln.mkz_2020
vehicle.mercedesccc.mercedesccc -> vehicle.mercedes.coupe_2020
vehicle.charger2020.charger2020 -> vehicle.dodge.charger_2020
vehicle.chargercop2020.chargercop2020  -> vehicle.dodge.charger_police_2020
vehicle.vespa.vespa -> vehicle.vespa.zx125
```
- `carla.Map.name` now returns the full path (so *Town01* now instead returns *Carla/Maps/Town01*)
- Agents API has had its initialization simplified.
- Adapted manual control to the new CARLA version

Additionally, fixed bug causing the watchdog to not correctly reset when using multiple repetitions

### Where has this been tested?

  * **Platform(s):** Ubutnu 18.04
  * **Python version(s):** 3.6
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** 0.9.12

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)

### CODE REVIEW

**Review by fabianoboril — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[scenario_runner.py, line 333 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/783#-MgW8Ot3DvFsq8nJtuD4:-MgW8Ot41S3hJfwFN334:b-bfvkwl) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/dfc9df55307291be090762785a77410cfaf4a422/scenario_runner.py#L333)):*
> ```Python
>             self.world.apply_settings(settings)
> 
>         CarlaDataProvider.set_client(self.client)
> ```

This line was moved up (right to where the client is configured) with one of the last commits to improve cleanup, if I am not mistaken.

**Comment by raymanfx** [comment]
Is this going to be merged some time soon? Carla 0.9.12 has been out for a few days now. I tested this PR and it works fine for our use cases :)

Let me know whether there is more work required (which I could help with).

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: 24 of 28 files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[scenario_runner.py, line 333 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/783#-MgW8Ot3DvFsq8nJtuD4:-MiL0j5OC-UsksW4Y8a3:bbv7hgk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/840f4dc93605f689e9a49e35115e54c3e0650372/scenario_runner.py#L333)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

This line was moved up (right to where the client is configured) with one of the last commits to improve cleanup, if I am not mistaken.
</blockquote></details>

Yes, due to repetitions. At the end of one repetition this is cleaned up, and if not reinitialized again, it breaks

**Review by fabianoboril — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: all files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[scenario_runner.py, line 44 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/783#-MiMlIOZCMMqzP1DU3o4:-MiMlIOZCMMqzP1DU3o5:bdfvkv6) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/23800e6b3910af7b59de040f3b2aa2c59222dabf/scenario_runner.py#L44)):*
> ```Python
> 
> # Version of scenario_runner
> VERSION = '0.9.12'
> ```

Can you also update https://github.com/carla-simulator/scenario_runner/blob/master/CARLA_VER?

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: 30 of 31 files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[scenario_runner.py, line 44 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/783#-MiMlIOZCMMqzP1DU3o4:-MiQdAOW7eZLavPjVrJ1:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/23800e6b3910af7b59de040f3b2aa2c59222dabf/scenario_runner.py#L44)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Can you also update https://github.com/carla-simulator/scenario_runner/blob/master/CARLA_VER?
</blockquote></details>

Done.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/783)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glopezdiest)

**Pull request merged**
