### PR TITLE
Added multiple locations to TrafficScenario 02 and 03

### PR DESCRIPTION
**Pull request by zaaramariyam**
- Added Multiple locations to TrafficScenario 02.

Where has this been tested?

    Platform(s): 18.04
    Python version(s): 2.7
    Unreal Engine version(s): ...
    CARLA version: ... 0.9.3

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/30)

### CODE REVIEW

**Comment by fabianoboril** [comment]
I haven't yet tested the scenarios. Code looks ok.

**Comment by zaaramariyam** [comment]
1. Fixed typo.
2. Updated config file for Traffic Scenario 03.

**Comment by nishanthjois** [comment]
```
 <scenario name="FollowLeadingVehicle_3" type="FollowLeadingVehicle" town="Town02">
        <ego_vehicle x="-3.5" y="295" z="0.22" yaw="270" model="vehicle.lincoln.mkz2017" />
        <other_actor x="-3.6" y="265" z="0.22" yaw="270" model="vehicle.mini.cooperst" />
   </scenario>
```

We get below error on spawning **'vehicle.mini.cooperst'** only in Town 02 [this issue does not occur on spawing other vechiles at same location]
> _Error: Unable to spawn vehicle vehicle.mini.cooperst at Transform(Location(x=-3.6, y=265, z=0.22), Rotation(pitch=0, yaw=270, roll=0))_

**Comment by zaaramariyam** [comment]
@fabianoboril 
1. Keep lane change for other actors(bike) is returning the status as Failure, as it is crossing the solid lane. Can we remove this check? 
2. I fixed the other actors in FollowLeadingVehicle(Town02), instead of taking them randomly, to solve "the other_actor cannot be spawned/Collision error".

**Comment by fabianoboril** [comment]
Any updates regarding my comments?

**Comment by fabianoboril** [comment]
Please rebase

**Comment by zaaramariyam** [comment]
Closing this PR for now.

**Pull request closed without merging**
