### PR TITLE
Added support for LongitudinalDistanceAction

### PR DESCRIPTION
**Pull request by sagar-g-v**
#### Description

1) Added implementation for [ `LongitudinalDistanceAction`](https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/LongitudinalDistanceAction.html)

for Testing all attributes imploementation use this XOSC 
  - [LDistanceActionTest.txt](https://github.com/carla-simulator/scenario_runner/files/6674481/LDistanceActionTest.txt)

  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8
  * **Unreal Engine version(s):**  -
  * **CARLA version:** 0.9.11

#### Possible Drawbacks
There is a limitation in calculating `longitudinal` distance at some juctions, but it can be improved in the future work.
as of now using `cartesianDistance` in such cases.

Regards,
Sagar GV

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)* status: all files reviewed, 3 unresolved discussions (waiting on @sagar-g-v)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 2905 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlPjP22AJ6qnwB7eH:-McSlPjP22AJ6qnwB7eI:b6lo9uk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2905)):*
> ```Python
>         ref_actor_wp = CarlaDataProvider.get_map().get_waypoint(ref_actor_transform.location)
>         same_lane, _, _ = sr_tools.scenario_helper.same_road_info(actor_wp, ref_actor_wp)
>         if is_within_distance_ahead(ref_actor_transform, actor_transform, self._gap) and same_lane:
> ```

Why do we need same lane here? For example, in OpenDRIVE it may happen that the ID changes because a new lane was added (like a ramp for a highway), which may cause this to be false? Why not simply calculating the distance along the road/route (there should be a method for this within the helper methods).
___
*[srunner/tools/openscenario_parser.py, line 1075 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlB0u-5-ZXZ8OiD4g:-McSlB0v8tEsZCUt4UKR:b-s183cd) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/tools/openscenario_parser.py#L1075)):*
> ```Python
>                         gap_type, gap = 'distance', float(long_dist_action.attrib.get('distance', 0))
>                     elif "timeGap" in long_dist_action.attrib and "distance" not in long_dist_action.attrib:
>                         raise NotImplementedError("LongitudinalDistanceAction: timeGap is not implemented")
> ```

Having the speed of the actors, we can convert the time gap into a distance gap inside the atomic_maneuver class (within the update() function). Or not?
___
*[srunner/tools/scenario_helper.py, line 569 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlszgCEFdPNIp6txA:-McSlszgCEFdPNIp6txB:b-p16apf) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/tools/scenario_helper.py#L569)):*
> ```Python
> 
> 
> def get_distance_between_actors(current, target, distance_type="euclidianDistance", freespace=False,
> ```

Did you check that this re-factoring is not causing problems?

**Comment by sagar-g-v** [comment]
> > Reviewed 2 of 5 files at r2, 5 of 5 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)_ status: all files reviewed, 3 unresolved discussions (waiting on @sagar-g-v)
> 
> _[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 2905 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlPjP22AJ6qnwB7eH:-McSlPjP22AJ6qnwB7eI:b6lo9uk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2905)):_
> 
> > ```python
> >         ref_actor_wp = CarlaDataProvider.get_map().get_waypoint(ref_actor_transform.location)
> >         same_lane, _, _ = sr_tools.scenario_helper.same_road_info(actor_wp, ref_actor_wp)
> >         if is_within_distance_ahead(ref_actor_transform, actor_transform, self._gap) and same_lane:
> > ```
> 
> Why do we need same lane here? For example, in OpenDRIVE it may happen that the ID changes because a new lane was added (like a ramp for a highway), which may cause this to be false? Why not simply calculating the distance along the road/route (there should be a method for this within the helper methods).
> 

Yes, you are right, same lane will not work if ex: -1 lane of one raod is connected to -2 lane of other road. for getting longitudinal distance i change it to use calculate_distance with global_planner. but i want to make sure both actors are along same path, is there a simple way to do it?
> _[srunner/tools/openscenario_parser.py, line 1075 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlB0u-5-ZXZ8OiD4g:-McSlB0v8tEsZCUt4UKR:b-s183cd) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/tools/openscenario_parser.py#L1075)):_
> 
> > ```python
> >                         gap_type, gap = 'distance', float(long_dist_action.attrib.get('distance', 0))
> >                     elif "timeGap" in long_dist_action.attrib and "distance" not in long_dist_action.attrib:
> >                         raise NotImplementedError("LongitudinalDistanceAction: timeGap is not implemented")
> > ```
> 
> Having the speed of the actors, we can convert the time gap into a distance gap inside the atomic_maneuver class (within the update() function). Or not?
> 
Yes, This is definetly possible, i will change that and confirm.
> _[srunner/tools/scenario_helper.py, line 569 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McSlszgCEFdPNIp6txA:-McSlszgCEFdPNIp6txB:b-p16apf) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/200ce2a35d877893fa7602cd7209af0bb5d1bdf7/srunner/tools/scenario_helper.py#L569)):_
> 
> > ```python
> > def get_distance_between_actors(current, target, distance_type="euclidianDistance", freespace=False,
> > ```
> 
> Did you check that this re-factoring is not causing problems?
>
Yes I have checked the usage, it is giving the same result when i interchaged it.

I will make these changes and run some tests and then update here.

Regards,
Sagar G V

**Comment by sagar-g-v** [comment]
Hi @fabianoboril,  

I tried to add `timeGap` also here but i observed that it is not stable. ex: for timegap=10 it is fluctuating between 15 to 5 and sometimes colliding.

logitudinal distance calculation is working fine with global_planner.

as of now it is only checking if target vehicle is ahead and is within gap.
also in OSC doucmentation it is not mentioned whether to check if reference entity is blocking the lane or not. it is only talking about gap.

https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/LongitudinalDistanceAction.html

Regards,
Sagar G V

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)* status: all files reviewed, 4 unresolved discussions (waiting on @fabianoboril and @sagar-g-v)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 2908 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmFgu-2KKoITRzQi3I:-McmFgu-2KKoITRzQi3J:bywh5r0) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2908)):*
> ```Python
>         actor_transform = CarlaDataProvider.get_transform(self._actor)
>         ref_actor_transform = CarlaDataProvider.get_transform(self._reference_actor)
>         if is_within_distance_ahead(ref_actor_transform, actor_transform, float('inf')) and \
> ```

Do we still need this is_within_distance_ahead here? It seems redundant with the gap calculation
___
*[srunner/tools/scenario_helper.py, line 589 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmG6NVERE-9Lr--Wwr:-McmG6NVERE-9Lr--Wws:bbh9a0v) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/tools/scenario_helper.py#L589)):*
> ```Python
>             distance = 0
>             # Get the route
>             route = global_planner.trace_route(current_transform.location, target_transform.location)
> ```

What about cars that are on the opposite lane? The route might provide a much much longer distance than the actual headway distance.

**Comment by sagar-g-v** [comment]
> _[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 2908 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmFgu-2KKoITRzQi3I:-McmFgu-2KKoITRzQi3J:bywh5r0) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2908)):_
> 
> > ```python
> >         actor_transform = CarlaDataProvider.get_transform(self._actor)
> >         ref_actor_transform = CarlaDataProvider.get_transform(self._reference_actor)
> >         if is_within_distance_ahead(ref_actor_transform, actor_transform, float('inf')) and \
> > ```
> 
> Do we still need this is_within_distance_ahead here? It seems redundant with the gap calculation

Yes becase this will make sure if the vehicle is in front. no need follow if the vehicle is behind
it is not used for gap chek, so distance is give as infinite.

> _[srunner/tools/scenario_helper.py, line 589 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmG6NVERE-9Lr--Wwr:-McmG6NVERE-9Lr--Wws:bbh9a0v) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/tools/scenario_helper.py#L589)):_
> 
> > ```python
> >             distance = 0
> >             # Get the route
> >             route = global_planner.trace_route(current_transform.location, target_transform.location)
> > ```
> 
> What about cars that are on the opposite lane? The route might provide a much much longer distance than the actual headway distance.

when cars on opposite side and on same road it will jump to else condition, it will not use global_planner.

**Review by fabianoboril — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)* status: all files reviewed, 4 unresolved discussions (waiting on @fabianoboril and @sagar-g-v)

___
*[srunner/scenariomanager/scenarioatomics/atomic_behaviors.py, line 2908 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmFgu-2KKoITRzQi3I:-McnmcA7DtO6zYAT_IAx:b-sitikh) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2908)):*
<details><summary><i>Previously, sagar-g-v (Sagar G V) wrote…</i></summary><blockquote>

Yes becase this will make sure if the vehicle is in front. no need follow if the vehicle is behind
it is not used for gap chek, so distance is give as infinite.

</blockquote></details>

ah ok :)
___
*[srunner/tools/scenario_helper.py, line 589 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/770#-McmG6NVERE-9Lr--Wwr:-Mcnn2pG5bPAII5WwJPZ:bxt5d0e) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/5359a550df584364df3aa0bd587c73e1d37dc3b0/srunner/tools/scenario_helper.py#L589)):*
<details><summary><i>Previously, sagar-g-v (Sagar G V) wrote…</i></summary><blockquote>

when cars on opposite side and on same road it will jump to else condition, it will not use global_planner.
</blockquote></details>

hm... fair call

**Comment by fabianoboril** [comment]
Hi,
is this PR completed? Anything you want to add for handling the time gaps?

**Comment by sagar-g-v** [comment]
> Hi,
> is this PR completed? Anything you want to add for handling the time gaps?

As of now i have not done anything related to timegap, but will raise seprerate PR when it is done.

**Review by fabianoboril — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/770)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sagar-g-v)

**Pull request merged**
