### PR TITLE
Blocked intersection

### PR DESCRIPTION
**Pull request by TayYim**
#### Description

Add Blocked Intersection (AKA Junction turn into non-visible vehicle)

I didn't include weather changes because it doesn't seem helpful.

User need to specify the location of the blocker vehicle.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** leaderboard-2.0 branch

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)

### CODE REVIEW

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenarios/blocked_intersection.py` line 66 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47EM0J8kZPhEGKU1TU:-N47EM0J8kZPhEGKU1TV:b-bvg816) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L66)):*
> ```Python
>         self._block_time = 5  # s
> 
>         self._obstacle_horizontal_gap = 2  # m
> ```

The whole obstacle creation feels weird. I think that there should only be 1 by default, but can more can be added with the extra obstacle parameter.

Also, I'd parametrize both the gap between obstacles as well as its blueprint, so that different zones can have different obstacles



_Suggestion:_
```Python
        self._obstacle_horizontal_gap = 2  # m
        self._obstacle_vertical_gap = 2  # m
        self._obstacle_model = "static.prop.trampoline"
        self._obstacle_amount = 6  # Extra obstacles are not included
```
___
*[`srunner/scenarios/blocked_intersection.py` line 67 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47EJUx7ukNl7oha3Ya:-N47EJUx7ukNl7oha3Yb:b-yrumkl) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L67)):*
> ```Python
> 
>         self._obstacle_horizontal_gap = 2  # m
>         self._obstacle_vertical_gap = 2  # m
> ```

Unused



_Code quote:_
```Python
self._obstacle_vertical_gap = 2  # m
```
___
*[`srunner/scenarios/blocked_intersection.py` line 97 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47CGjc56PZY6c1qniP:-N47CGjd3yZSGgjIKB0s:b-9eddrq) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L97)):*
> ```Python
>             right_wp = sidewalk_waypoint.get_right_lane()
>             if right_wp is None:
>                 break  # No more right lanes
> ```

Is the scenario prepared to run outside sidewalks? If not, this should raise an error



_Code quote:_
```Python
            if right_wp is None:

                break  # No more right lanes
```
___
*[`srunner/scenarios/blocked_intersection.py` line 141 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47DeIB7Y9aM64bCGSA:-N47DeIB7Y9aM64bCGSB:b-rigvar) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L141)):*
> ```Python
>             sequence.add_child(RemoveJunctionEntry(
>                 [self._reference_waypoint, self._blocker_waypoint], all_road_entries=True))
>             sequence.add_child(SwitchLane(
> ```

Is there really a need to do this? Shouldn't the blocker close enough to the dungeon as to not block the exit? Also, with this, the road after the scenario will be completely empty of BA actors



_Code quote:_
```Python
            sequence.add_child(SwitchLane(

                self._blocker_waypoint.lane_id, False))
```

**Review by TayYim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @glopezdiest)

___
*[`srunner/scenarios/blocked_intersection.py` line 66 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47EM0J8kZPhEGKU1TU:-N4_8cqoDGmd5WifiAsp:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L66)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

The whole obstacle creation feels weird. I think that there should only be 1 by default, but can more can be added with the extra obstacle parameter.

Also, I'd parametrize both the gap between obstacles as well as its blueprint, so that different zones can have different obstacles
</blockquote></details>

Done.
___
*[`srunner/scenarios/blocked_intersection.py` line 67 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47EJUx7ukNl7oha3Ya:-N4_3sXQ2YWGeODaiJqW:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L67)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`srunner/scenarios/blocked_intersection.py` line 97 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47CGjc56PZY6c1qniP:-N4_CKym1iunTP8SMuJ0:b-bg19v8) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L97)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Is the scenario prepared to run outside sidewalks? If not, this should raise an error
</blockquote></details>

Done. This scenario is expected to spawn obstacles on the sidewalk.
Add error raising and doc.
___
*[`srunner/scenarios/blocked_intersection.py` line 141 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N47DeIB7Y9aM64bCGSA:-N4_DMnFD4fINqZj1cUQ:b-aqo8rc) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/6f309661d4552a2716fb34aa888ef56545fcb1a6/srunner/scenarios/blocked_intersection.py#L141)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Is there really a need to do this? Shouldn't the blocker close enough to the dungeon as to not block the exit? Also, with this, the road after the scenario will be completely empty of BA actors
</blockquote></details>

Done.
Not really needed if the blocker is close enough to the beginning of the lane, which is expected.

**Review by glopezdiest — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenarios/blocked_intersection.py` line 156 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N4_ykEl586oHlkmghpa:-N4_ykEmAmywc9mWD0eX:betmosh) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7f59293bff8206e821e5912185fe018c36bdd2e5/srunner/scenarios/blocked_intersection.py#L156)):*
> ```Python
>         blocker_wait = py_trees.composites.Parallel("Wait for ego to come close",
>                                                     policy=py_trees.common.ParallelPolicy.SUCCESS_ON_ONE)
>         blocker_wait.add_child(InTriggerDistanceToVehicle(
> ```

The parallel is useless here



_Code quote:_
```Python
        blocker_wait = py_trees.composites.Parallel("Wait for ego to come close",

                                                    policy=py_trees.common.ParallelPolicy.SUCCESS_ON_ONE)

        blocker_wait.add_child(InTriggerDistanceToVehicle(

            self.other_actors[-1], self.ego_vehicles[0],  self._block_distance))
```

**Review by TayYim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @glopezdiest)

___
*[`srunner/scenarios/blocked_intersection.py` line 156 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/901#-N4_ykEl586oHlkmghpa:-N4dvTSx3RKH248G3rLa:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7f59293bff8206e821e5912185fe018c36bdd2e5/srunner/scenarios/blocked_intersection.py#L156)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

The parallel is useless here
</blockquote></details>

Done.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TayYim)

**Comment by glopezdiest** [comment]
After some testing, the extra obstacles don't seem to be working properly, as only one them is being spawned. There transform seems to be the same for all obstacles.

Further considerations, we might want to make it work for junctions with no sidewalk, and have a method to add obstacles inside of the junction. We can discuss this afte rthe PR is merged though, when we start extensive testing on the scenario, and its locations

**Comment by TayYim** [comment]
> After some testing, the extra obstacles don't seem to be working properly, as only one them is being spawned. There transform seems to be the same for all obstacles.

Fixed.

> we might want to make it work for junctions with no sidewalk

This one is easy to do, I think.

> and have a method to add obstacles inside of the junction. We can discuss this after the PR is merged though, when we start extensive testing on the scenario, and its locations

Sure. Discuss it later.

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TayYim)

**Pull request merged**
