### PR TITLE
Fix for crash in Traffic Scenario 05

### PR DESCRIPTION
**Pull request by zaaramariyam**
#### Description
Added avoid collision flag, and adversary vehicle now doesn't crash with any other vehicle. 

Fixes #  

#### Where has this been tested?

  * **Platform(s):** 18.04
  * **Python version(s):**2.7
  * **Unreal Engine version(s):**4.21
  * **CARLA version:**0.9.5

#### Possible Drawbacks
None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/164)

### CODE REVIEW

**Comment by zaaramariyam** [comment]
Made few changes after testing in challenge_evaluator.

**Comment by fabianoboril** [comment]
Please rebase and focus your commit only on the things you have changed.

**Comment by zaaramariyam** [comment]
Rebased.

**Comment by zaaramariyam** [comment]
> Please rebase and focus your commit only on the things you have changed.

Done.

**Pull request merged**
