### PR TITLE
Supporting several additional OpenScenario 1.0 tags 

### PR DESCRIPTION
**Pull request by synkrotron**
#### Description

We've added some new tags that weren't supported before, as shown in Changelog.md and openscenario_support.md.

#### Where has this been tested?

  * **Platform(s): ** ubuntu 20.04
  * **Python version(s):** python 3.8.10
  * **Unreal Engine version(s):**  UE4
  * **CARLA version:** 0.9.13

#### Possible Drawbacks

We did complete tests and found no errors.

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1014)

### CODE REVIEW

**Comment by synkrotron** [comment]
@glopezdiest We have re-created the PR for openscenario 1.0 new tags support, please ignore previous one #987

**Comment by germanros1987** [comment]
@joel-mb can you review this, please?

**Comment by ronyshaji** [comment]
@synkrotron Hey, I tried it and seems like there is some issue with waypoint based scenarios. Do you tried with waypoint based scenarios also?

**Comment by synkrotron** [comment]
> @synkrotron Hey, I tried it and seems like there is some issue with waypoint based scenarios. Do you tried with waypoint based scenarios also?

Hello, do you have an example?

**Comment by ronyshaji** [comment]
> > @synkrotron Hey, I tried it and seems like there is some issue with waypoint based scenarios. Do you tried with waypoint based scenarios also?
> 
> Hello, do you have an example?

Hey, I just posted this in https://github.com/guardstrikelab/scenario_runner as an issue.

**Comment by glopezdiest** [comment]
Hey @synkrotron, could you please resolve the conflicts so that we can merge the PR?

**Comment by synkrotron** [comment]
Hi, @germanros1987, I resolved the code conflict by deleting the original branch 'feature/new_tags_support' and creating a new one (also named 'feature/new_tags_support') based on the master branch. However, it appears that this Pull Request has not been updated. Should I close this PR and create a new one?

**Review by glopezdiest — APPROVED** [review]
> Reviewed 6 of 11 files at r1, 1 of 5 files at r2, 3 of 5 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1014)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)

**Comment by glopezdiest** [comment]
That's okay, there are no more conflicts, so we can merge the PR

**Pull request merged**
