### PR TITLE
ParameterAction implementation

### PR DESCRIPTION
**Pull request by sagar-g-v**
#### Description

Main changes made for implementing ParameterAction are.

1) Adding new class `ParameterRef` which will allow referencing parameter during the tick (runtime) and get the modified parameter value. also in future implementation(which i am currently working on) this class will be able to interpret math expression (which is required for OSC1.1)
Previously, all parameter reference was replaced with value during parsing and due to this it was not possible to get the new value of parameters. this was problemetic when ParameterAction was permormed inside story.

2) ParameterCondition was only working for criterias, so it is now updated for all parameters.

Example Scenario to test: [LDistanceActionTest.zip](https://github.com/carla-simulator/scenario_runner/files/6930752/LDistanceActionTest.zip)

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):**  3.8
  * **Unreal Engine version(s):** 
  * **CARLA version:** 0.9.11

#### Possible Drawbacks

This may not consider parameters from catalogs. need to check with catalog refrences.

Regards,
Sagar G V

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)

### CODE REVIEW

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)* status: all files reviewed, 1 unresolved discussion (waiting on @sagar-g-v)

___
*[srunner/tools/openscenario_parser.py, line 935 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwAQUA4mvB63K1NTx-:-MhwAQUB239CCd2Kw31F:b-r85wjk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7e5bf2f0c5667fb2bf23409c143ba52e32809d64/srunner/tools/openscenario_parser.py#L935)):*
> ```Python
>                 elif entity_condition.find('AccelerationCondition') is not None:
>                     accel_condition = entity_condition.find('AccelerationCondition')
>                     condition_value = ParameterRef(accel_condition.attrib.get('value'))
> ```

I am not getting the benefit of changing this. Can you elaborate a little on this change?

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @fabianoboril and @sagar-g-v)

___
*[srunner/scenarioconfigs/openscenario_configuration.py, line 395 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwHiEmDdUG8nKct34f:-MhwHiEmDdUG8nKct34g:b-d2pxcu) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/scenarioconfigs/openscenario_configuration.py#L395)):*
> ```Python
>                         for target in speed.iter('SpeedActionTarget'):
>                             for absolute in target.iter('AbsoluteTargetSpeed'):
>                                 speed = ParameterRef(absolute.attrib.get('value', 0))
> ```

I think a float-conversion is missing here. At least this fails in my testing scenarios. Why do we need this wrapper class?
___
*[srunner/tools/openscenario_parser.py, line 641 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwHbI89g-7B7oCwjcY:-MhwHbI89g-7B7oCwjcZ:b-exgoc2) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/tools/openscenario_parser.py#L641)):*
> ```Python
>                 orientation = rel_pos.find('Orientation')
>                 is_absolute = (orientation.attrib.get('type') == "absolute")
>                 dyaw = math.degrees(float(ParameterRef(orientation.attrib.get('h', 0))))
> ```

Here you convert again to float, elsewhere you are not doing that.

**Comment by sagar-g-v** [comment]
> > Reviewed 1 of 5 files at r2, 10 of 10 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)_ status: all files reviewed, 1 unresolved discussion (waiting on @sagar-g-v)
> 
> _[srunner/tools/openscenario_parser.py, line 935 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwAQUA4mvB63K1NTx-:-MhwAQUB239CCd2Kw31F:b-r85wjk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7e5bf2f0c5667fb2bf23409c143ba52e32809d64/srunner/tools/openscenario_parser.py#L935)):_
> 
> > ```python
> >                 elif entity_condition.find('AccelerationCondition') is not None:
> >                     accel_condition = entity_condition.find('AccelerationCondition')
> >                     condition_value = ParameterRef(accel_condition.attrib.get('value'))
> > ```
> 
> I am not getting the benefit of changing this. Can you elaborate a little on this change?

for example when use convert value to a float i.e `'12.3' converted to float` the conversion will be possible.
same conversion if do with parametrised value i.e `'$speed' converted to float` conversion will fail becasue the inbuild class `float` can not interpret the value of `$speed`.
https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/tools/openscenario_parser.py#L137-L142

this part of the code takes care of conersion of paramter reference to a numeric value, 
similarly there are other methods in this wrapper class https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/tools/openscenario_parser.py#L90 which will take care of other type conversion, math operation, comapriation operations

**Comment by sagar-g-v** [comment]
> > Reviewed 1 of 2 files at r6.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)_ status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @fabianoboril and @sagar-g-v)
> 
> _[srunner/scenarioconfigs/openscenario_configuration.py, line 395 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwHiEmDdUG8nKct34f:-MhwHiEmDdUG8nKct34g:b-d2pxcu) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/scenarioconfigs/openscenario_configuration.py#L395)):_
> 
> > ```python
> >                         for target in speed.iter('SpeedActionTarget'):
> >                             for absolute in target.iter('AbsoluteTargetSpeed'):
> >                                 speed = ParameterRef(absolute.attrib.get('value', 0))
> > ```
> 
> I think a float-conversion is missing here. At least this fails in my testing scenarios. Why do we need this wrapper class?
> 
> _[srunner/tools/openscenario_parser.py, line 641 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/784#-MhwHbI89g-7B7oCwjcY:-MhwHbI89g-7B7oCwjcZ:b-exgoc2) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/cd83b7b3896e7e15aa1e24e2d5ebd241f4e23f8a/srunner/tools/openscenario_parser.py#L641)):_
> 
> > ```python
> >                 orientation = rel_pos.find('Orientation')
> >                 is_absolute = (orientation.attrib.get('type') == "absolute")
> >                 dyaw = math.degrees(float(ParameterRef(orientation.attrib.get('h', 0))))
> > ```
> 
> Here you convert again to float, elsewhere you are not doing that.

as `math.degree` function is a library function i am not sure if this function converts input to float before using it, so i have converted parameter to float before passing it in.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 3 of 6 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/784)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sagar-g-v)

**Pull request merged**
