### PR TITLE
WIP: Generalization of Traffic Scenario 10

### PR DESCRIPTION
**Pull request by SubhashiniPerumal**
Updated the WaypointFollower behavior to use the plan set by generate_target_waypoint method

#### Description
Generalization of Traffic Scenario 10

Fixes #  

- Updated the sync arrival reference to intersection point

- Added WaypointFollower method which sets the route plan according to target waypoint

#### Where has this been tested?

  * **Platform(s):** ...18.04
  * **Python version(s):** ...2.7
  * **Unreal Engine version(s):** ...
  * **CARLA version:** ...0.9.3

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/72)

### CODE REVIEW

**Comment by fabianoboril** [comment]
The scenarios work, but the cleanup is somehow broken. If this is fixed, and the branch is based on current development, we can merge.

**Comment by fabianoboril** [comment]
I am sorry, there are new merge conflicts...

**Comment by SubhashiniPerumal** [comment]
> I am sorry, there are new merge conflicts...

PR is rebased. Kindly check.

**Comment by SubhashiniPerumal** [comment]
> > Reviewed 2 of 8 files at r4, 7 of 7 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/72)_ status: all files reviewed, 4 unresolved discussions (waiting on @SubhashiniPerumal)
> 
> _[srunner/scenarios/follow_leading_vehicle.py, line 63 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/72#-La0AOSbBgEBvln8eYKq:-La0AOScCJnAhkardcCy:bt6w9t7) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/bdfa37985b5002e9bdcf8fc328bb7a725d3912e0/srunner/scenarios/follow_leading_vehicle.py#L63)):_
> 
> > ```python
> >         self._other_actor_stop_in_front_intersection = 30  # Stop ~30m in front of intersection
> > 
> >         parameter_list = []
> > ```
> 
> Please remove all changes related to scenario 02. This will help to avoid merge conflicts for other PRs

Reverted the changes unrelated to this PR. Please check.

**Comment by SubhashiniPerumal** [comment]
Fixed the conflicts. Working on scenario implementation changes.

**Comment by fabianoboril** [comment]
Another rebase is required. What is the state of the implementation?

**Comment by fabianoboril** [comment]
Please let us know when you are done. Btw. another rebase is now required.

**Comment by SubhashiniPerumal** [comment]
The server is loading opendrive map repeatedly. This hampers local planner and waypoint follower functionality. The scenario continues normal execution once the loading stops. This happens unpredictably. Sometimes, the issue doesn't show itself at all and the scenario runs ok and sometimes the issue freezes the scenario for minutes. Need to further investigate what is causing the issue.

Please check the below video for current update : 
https://www.youtube.com/watch?v=PQXOoJCz_Uo&feature=youtu.be

**Comment by SubhashiniPerumal** [comment]
Please check the updated implementation.

**Comment by SubhashiniPerumal** [comment]
Implemented below behaviors:
1. To detect arrival of actors to a particular location and put them into blackboard queue
2. To stop the actors read from the blackboard queue
3. To prioritize the actors in the queue

Work in progress: To fix the issue with queue which has to passed to WaypointFollower

**Comment by SubhashiniPerumal** [comment]
Work in progress: To fix the timing issues with PriorityNegotiator

**Comment by fabianoboril** [comment]
I close this PR for now. If we decide to come back to this update, we can just re-open it.

**Pull request closed without merging**
