### PR TITLE
Generalization of TrafficScenario02

### PR DESCRIPTION
**Pull request by zaaramariyam**
#### Description
1. Generalized TrafficScenario02.
2. Added HandBrakeVehicle behavior for slopes.
3. Added WaypointFollower behavior.
4. Initialized other actors based on hero vehicle location.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ...18.04
  * **Python version(s):** ...2.7
  * **Unreal Engine version(s):** ...
  * **CARLA version:** ...0.9.3

#### Possible Drawbacks
- In Town02, sometimes vehicles are spawning, but sometimes it is showing collision at spawn point at same location.
Query: 
Is this problem because of pitch?

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/58)

### CODE REVIEW

**Comment by fabianoboril** [comment]
Please change this PR to development branch

**Comment by zaaramariyam** [comment]
> Please change this PR to development branch

Sure.I will change PR to development branch.

**Comment by zaaramariyam** [comment]
Moved the PR to development branch.

**Comment by fabianoboril** [comment]
Your changes look ok, but I cannot test the scenarios as long as there is a merge conflict.

**Comment by zaaramariyam** [comment]
> Your changes look ok, but I cannot test the scenarios as long as there is a merge conflict.

Done.

**Comment by fabianoboril** [comment]
I am sorry, there are new merge conflicts...

**Comment by fabianoboril** [comment]
Please fix the comment and there is one more rebase.

Regarding the issue with the generated target waypoint: @germanros1987 Is this something related to the issues the team is currently working on?

**Pull request merged**
