### PR TITLE
Generalisation of Traffic Scenario 03

### PR DESCRIPTION
**Pull request by akki6843**
as per the lane width.

#### Description
As per the requirements for Scenario 03, other_actor is supposed to either
stand or drive into middle of the road.
For this lane_width information is used.

Code has been tested against pep8 and pylint.

#### Where has this been tested?

  * **Platform(s):** ... Linux 18.04
  * **Python version(s):** ... 2.7
  * **CARLA version:** ... 0.9.4

#### Possible Drawbacks
Due to difference of lane width in Town03, 
spawning of actor is not accurate.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/68)

### CODE REVIEW

**Comment by fabianoboril** [comment]
Please rebase ontop of current development

**Comment by akki6843** [comment]
> Please rebase ontop of current development

Done

**Comment by fabianoboril** [comment]
I am sorry, there are new merge conflicts...

**Comment by akki6843** [comment]
> I am sorry, there are new merge confl

**Comment by akki6843** [comment]
> I am sorry, there are new merge conflicts...

Solved the new merge conflicts

**Comment by akki6843** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/68)_ status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @akki6843 and @fabianoboril)
> 
> _[srunner/configs/ObjectCrossing.xml, line 42 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/68#-La1-UnU9WrMxXGMXxhA:-La1-UnU9WrMxXGMXxhB:b-r0z9tj) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7abfb354c1078e668046abdfa0da2dfe29b1ac95/srunner/configs/ObjectCrossing.xml#L42)):_
> 
> > ```
> >         <ego_vehicle x="110" y="129" z="1" yaw="180" model="vehicle.lincoln.mkz2017" />
> >     </scenario>
> >     <scenario name="DynamicObjectCrossing_7" type="DynamicObjectCrossing" town="Town03">
> > ```
> 
> Setting the other actor does not always work appropriately (for example here). Please go through the scenarios again and check that a collision always takes place assuming a "non-intelligent" ego vehicle.

Yes, its been reported and a known issue because of different lane width.
I have mentioned the same in possible drawback.
Trying to get a more generalised way to cover Town03 also.

**Comment by akki6843** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/68)_ status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @akki6843 and @fabianoboril)
> 
> _[srunner/scenarios/object_crash_vehicle.py, line 35 at r3](https://reviewable.io/reviews/carla-simulator/scenario_runner/68#-La8bb_lBtNAWszXvFjK:-La8bb_lBtNAWszXvFjL:b9luksg) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/7abfb354c1078e668046abdfa0da2dfe29b1ac95/srunner/scenarios/object_crash_vehicle.py#L35)):_
> 
> > ```python
> >     """
> >     def __init__(self, world, ego_vehicle, other_actors, town, randomize=False, debug_mode=False, config=None):
> >         """
> > ```
> 
> rebase needed to use the new interface

Done

**Comment by akki6843** [comment]
> > ```
> > DynamicObjectCrossing_10
> > ```
> 
> I think the adversary actor should be deleted after a while for the dynamic cases.
> For the static cases, the adversary actor should go away after a while and then it should be destroyed. The reason behind this is that sometimes the ego-vehicle could hit the adversary, which changes adversary trajectory. The actor ends in the wrong location and could block the road forever.


Done
For static case adversary actor after sometimes move out of road and gets destroyed.
And for dynamic also adversary actor is destroyed after timeout

**Comment by akki6843** [comment]
> > ```
> > DynamicObjectCrossing_7
> > ```
> 
> This seems to be still a problem. For this given location the actor starts in the wrong location and moves too early.

Yes, its been reported and a known issue #1349
As soon as this issue gets solved we will get this one.

**Comment by fabianoboril** [comment]
Please rebase. I suggest to remove the problematic location from the XML for now.

**Comment by pravinblaze** [comment]
Done

> Please rebase. I suggest to remove the problematic location from the XML for now.

**Comment by fabianoboril** [comment]
Based on yesterdays discussion, I merge this PR

**Pull request merged**
