### PR TITLE
Added Construction scenario

### PR DESCRIPTION
**Pull request by MSiam**
#### Description

Added Construction Scenario Setup

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 3.7.9
  * **Unreal Engine version(s):** ...
  * **CARLA version:** 0.9.11

#### Possible Drawbacks

Unknown

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)

### CODE REVIEW

**Review by glopezdiest — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @MSiam)

___
*[srunner/scenarios/construction_crash_vehicle.py, line 97 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX6w_fA3HS5eiStZI_0:-MX6w_fA3HS5eiStZI_1:b65z108) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L97)):*
> ```
> lane_width
> ```
This is the lane width of the lane of the ego's start location, not of the lane where the construction is at. This isn't really an issue as in CARLA, all lane widths are the same but just so you know.
___
*[srunner/scenarios/construction_crash_vehicle.py, line 154 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX6w0xC9HmiIQV9Id3A:-MX6w0xC9HmiIQV9Id3B:b-ar6o0s) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L154)):*
> ```
>         lane_width = self.ego_vehicles[0].get_world().get_map().get_waypoint(
>             self.ego_vehicles[0].get_location()).lane_width
> ```
Several comments here:
1) This has already been calculated at around *_initialize_actors*, and map is also available with *self._wmap*.
2) As a general good practice, avoid doing`get_map()` as much as possible, as it is quite computationally heavy.
3) Unused
___
*[srunner/scenarios/construction_crash_vehicle.py, line 159 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX6zieDD5Vx6U_F_4u8:-MX6zieE7hfMqZKtWlRX:b-tmi4qi) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L159)):*
> ```
> actor_stand = TimeOut(15)
> ```
Recommended to use the atomic behavior Idle (https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L1769), not the TimeOut
___
*[srunner/scenarios/construction_crash_vehicle.py, line 163 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX7--d1DBPXkHStcUMa:-MX7--d1DBPXkHStcUMb:b-piuwa1) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L163)):*
> ```
>         for i, _ in enumerate(self.other_actors):
>             actors_removed.append(ActorDestroy(self.other_actors[i]))
> ```
This loop can be merged with the one below doing something like

```
for i, _ in enumerate(self.other_actors):
    scenario_sequence.add_child(ActorDestroy(self.other_actors[i]))
```
___
*[srunner/scenarios/construction_crash_vehicle.py, line 170 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX70TXXBschjXHj0CGB:-MX70TXXBschjXHj0CGC:bgeox79) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L170)):*
> ```
>         root = py_trees.composites.Parallel(
>             policy=py_trees.common.ParallelPolicy.SUCCESS_ON_ONE)
> ```
This parallel behavior one has one child, *scenario_sequence*, so it isn't really needed. Better to directly return *scenario_sequence*
___
*[srunner/scenarios/construction_crash_vehicle.py, line 178 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/744#-MX6ysyn8sHaMs9BGjIk:-MX6ysyn8sHaMs9BGjIl:b-yei7jk) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/3caf51ac861b69af6fe246228d56ea613b4de246/srunner/scenarios/construction_crash_vehicle.py#L178)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         for i, _ in enumerate(self.other_actors):
>             scenario_sequence.add_child(
>                 ActorTransformSetter(
>                     self.other_actors[i],
>                     self.transforms[i]))
> ```
</details>

The ActorTransformSetter is useful to move actors at runtime, but here it isn't really needed, as their transforms is already set when being spawned

**Comment by glopezdiest** [comment]
Hey @MSiam, just reviewed your PR. The scenario is working fine and I haven't found any major errors. Left some code comments, specially at the behavior part (can be simplified by a lot).

Lastly, the way the cones are positioned feels weird to me. The most natural arrangement for them would be achieved by:
1) Removing the perpendicular ones that are closest to the construction sign:
2) Increasing the distance between cones parallel to the ego
3) Creating some kind of diagonal with the ending cones

image

This is definitely just my personal opinion and feel free to ignore it if you like the current arrangement.

**Comment by MSiam** [comment]
Thanks. - For lane_width: I understand yes that its for the ego car, but since I always locate the setup in the same lane its the same. The induced behaviour is to ensure the car can learn to maneuvour the setup and change lane back. - I modified all the rest of the comments except the diagonal lane which you mentioned was not necessary so I thought its ok. But I have three questions on behaviours: (1) Whenever I use Idle() as a child node in the sequence it fails with an error I am not quite sure why? (2) The other question is regarding the end_condition I thought by determining this distance it will measure that if this distance is covered by the ego car it will stop the scenario. am I wrong? (3) So if I want to add an modified basic agent behaviour to avoid obstacles I should implement a new class for it inheriting from AtomicBehaviours?

**Review by glopezdiest — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MSiam)

**Comment by glopezdiest** [comment]
> The other question is regarding the end_condition I thought by determining this distance it will measure that if this distance is covered by the ego car it will stop the scenario

That is partially correct. Your current behavior is a sequence of _Wait for X secs -> Destroy all actors -> Wait for the ego to move X meters_. Therefore, the distance moved by the ego doesn't start to be computed until the X secs have passed. If you want to make it such that the distance is computed from the beginning, you have to use a parallel behavior tree ([here](https://github.com/carla-simulator/scenario_runner/blob/master/srunner/scenarios/control_loss.py#L130) is one of many examples). _Wait for either X secs or the ego to move X meters -> Then destroy all actors_.

> So if I want to add a modified basic agent behaviour to avoid obstacles I should implement a new atomic behaviour for it?

That's definitely up to you. You can either use several small atomic behaviours to control any actor, or create a much more complex one. You can also use "external controls", as we do in OpenScenario (check [here](https://github.com/carla-simulator/scenario_runner/tree/master/srunner/scenariomanager/actorcontrols)), or you can find a new way altogether

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MSiam)

**Review by glopezdiest — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MSiam)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MSiam)

**Comment by fabianoboril** [comment]
I fixed the Static Code checks, that was an issue on our side. Can you add a comment to the CHANGELOG? Then we can merge it.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MSiam)

**Pull request merged**
