### PR TITLE
TimeToCollisionCondition and TimeToHeadwayCondition tags are improvised.

### PR DESCRIPTION
**Pull request by Sumza**
#### Description

`InTimeToArrivalToVehicle` class has been modified to support `TimeToCollisionCondition` tag for dynamic actors.

The formula used for  TimeToCollision calculation in previous Implementation is : 

```math
  Relative Distance = Distance between centre location of two actors.
  TimeToCollision = (2 * Relative Distance ) /  relative velocity of two actors
```

The formula used for  TimeToCollision calculation in current implementation is : 
```math
Relative Distance = Distance between centre location of two actors.
TimeToCollision = (Relative Distance - half of length of actor1 -  half of length of actor2 ) / relative velocity of two actors.
```
The modified calculation is done as in the below image :
ttc

The class `InTimeToArrivalToVehicle` is updated such that `TimeToHeadwayCondition` tag behaviour is not effected.

#### Where has this been tested?

  * **Platform(s):**  Ubuntu 18.04
  * **Python version(s):**  Python 3.6
  * **Unreal Engine version(s):**  
  * **CARLA version:**  CARLA_0.9.10
#### Possible Drawbacks : None

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/665)

### CODE REVIEW

**Comment by glopezdiest** [comment]
Hey @Sumza, thanks for the PR. One question regarding the formula you used. According to the OSC docs, the distance calculated is the one between reference points, and only if the *freespace* attribute is active that the bounding boxes are taken into account. However, your new implementation formula always takes them into account. Is my understanding correct?

**Comment by Sumza** [comment]
Hi @glopezdiest , Thanks for the feedback. Above point is noted and i will be creating a new class for ```TimeToCollisionCondition ``` and considering the freespace attribute. 
I will be creating a new PR for the above mentioned points.

**Comment by glopezdiest** [comment]
Hey, I just saw your other PR (#666) so can we consider this one as closed?

**Comment by Sumza** [comment]
Hi, Yes you can consider this as closed and consider the new PR for review. Thankyou!

**Pull request closed without merging**
