### PR TITLE
Generalization of Traffic Scenario 01

### PR DESCRIPTION
**Pull request by SubhashiniPerumal**
#### Description
Generalization of Traffic Scenario 01.

Fixes #  
Added noise to steer as well as throttle of the vehicle.

#### Where has this been tested?

  * **Platform(s):** ...18.04
  * **Python version(s):** ...2.7
  * **Unreal Engine version(s):** ...
  * **CARLA version:** ...0.9.3

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/56)

### CODE REVIEW

**Comment by fabianoboril** [comment]
The code seems fine. Let me try to run the scenarios, then we can merge this PR

**Comment by SubhashiniPerumal** [comment]
Modified the trigger and end conditions of the scenario.

**Comment by fabianoboril** [comment]
Please use development branch for PR

**Comment by fabianoboril** [comment]
Code works, but you need to rebase your branch to be on development branch.

**Comment by SubhashiniPerumal** [comment]
Thanks. I rebased and moved the PR to development branch.

**Pull request merged**
