### PR TITLE
Implementation of TrafficScenario 05

### PR DESCRIPTION
**Pull request by zaaramariyam**
#### Description
Implementation of Traffic Scenario 05.
Added multiple locations.

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ... 18.04
  * **Python version(s):** ... 2.7
  * **Unreal Engine version(s):** ...
  * **CARLA version:** ... 0.9.3

#### Possible Drawbacks
When we run the scenario, other actors are not accelerating in sync even though both are moving with same speed. 

Looking into it.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/63)

### CODE REVIEW

**Comment by zaaramariyam** [comment]
Fixed the traffic light issue based on Fabian's implementation on traffic light access.

**Comment by zaaramariyam** [comment]
> > Reviewed 2 of 3 files at r1, 5 of 7 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/63)_ status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @zaaramariyam)
> 
> _[manual_control.py, line 295 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/63#-L_8KpIq-YQDSzO1Lk8k:-L_8KpIq-YQDSzO1Lk8l:b-p1ruhl) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/dd0ce93e31e7f1b74a71b9e1fafd29e4807d25b9/manual_control.py#L295)):_
> 
> > ```python
> >             '',
> >             'Vehicle: % 20s' % get_actor_display_name(world.vehicle, truncate=20),
> >             'Map:     % 20s' % 'SomeMap', # world.world.get_map().name, # TODO: Fix this !
> > ```
> 
> Please update to current master branch!
> Sure. I will update.
> _[scenario_runner.py, line 182 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/63#-L_8L0Dg9Vwug4HKHG3g:-L_8L0Dg9Vwug4HKHG3h:bksgh9w) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/dd0ce93e31e7f1b74a71b9e1fafd29e4807d25b9/scenario_runner.py#L182)):_
> 
> > ```python
> >             self.ego_vehicle.set_transform(config.ego_vehicle.transform)
> > 
> >         actor_parameters = scenario_class.initialize_actors(self.ego_vehicle)
> > ```
> 
> Please see my comments for the scenario02 PR
> okay
> _[srunner/scenarios/leading_vehicle_decelerate.py, line 49 at r2](https://reviewable.io/reviews/carla-simulator/scenario_runner/63#-L_8L6sn3CCswidd64ug:-L_8L6sn3CCswidd64uh:b-k3fgps) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/dd0ce93e31e7f1b74a71b9e1fafd29e4807d25b9/srunner/scenarios/leading_vehicle_decelerate.py#L49)):_
> 
> > ```python
> >         parameter_list = []
> > 
> >         model_1 = 'vehicle.volkswagen.t2'
> > ```
> 
> Why not specifying these in the XML?

**Comment by zaaramariyam** [comment]
Moved the PR to development branch.

**Comment by zaaramariyam** [comment]
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/63)_ status: all files reviewed, 8 unresolved discussions (waiting on @zaaramariyam)
> 
> _[scenario_runner.py, line 182 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/63#-L_N_mP297KY6FbF_FY5:-L_N_mP32E5-pQNyqLpN:b-v7eu6m) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/fc6cece57b769b05733247a2849ec7348b2e5b87/scenario_runner.py#L182)):_
> 
> > ```python
> >             self.ego_vehicle.set_transform(config.ego_vehicle.transform)
> > 
> >         actor_parameters = scenario_class.initialize_actors(self.ego_vehicle)
> > ```
> 
> Please see PR #73 (Added CarlaActorPool to CarlaDataProvider) This should resolve this issue!



> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/63)_ status: all files reviewed, 8 unresolved discussions (waiting on @zaaramariyam)
> 
> _[scenario_runner.py, line 182 at r5](https://reviewable.io/reviews/carla-simulator/scenario_runner/63#-L_N_mP297KY6FbF_FY5:-L_N_mP32E5-pQNyqLpN:b-v7eu6m) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/fc6cece57b769b05733247a2849ec7348b2e5b87/scenario_runner.py#L182)):_
> 
> > ```python
> >             self.ego_vehicle.set_transform(config.ego_vehicle.transform)
> > 
> >         actor_parameters = scenario_class.initialize_actors(self.ego_vehicle)
> > ```
> 
> Please see PR #73 (Added CarlaActorPool to CarlaDataProvider) This should resolve this issue!

Okay

**Comment by fabianoboril** [comment]
This PR seems outdated, some comments are still open. Please update to recent development.

**Comment by zaaramariyam** [comment]
Working on minor changes related to HandBrake.

**Comment by zaaramariyam** [comment]
PR is ready for review.

**Comment by fabianoboril** [comment]
Based on yesterdays discussion I merge this PR

**Pull request merged**
