### PR TITLE
Removed illegal escape on [] around CDATA in junit xml.

### PR DESCRIPTION
**Pull request by AzaelCicero**
#### Description

The generated XML result file is ill formatted. 
I have discovered the problem when I tried to generate HTML version of results from XML generated by scenario runner. 
Input: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="1" disabled="0" errors="0" timestamp="2021-06-14 07:45:16" time="44.30" name="Simulation" package="Scenarios">
  <testsuite name="AsWaypointFollower_2" tests="2" failures="1" disabled="0" errors="0" time="44.30">
    <testcase name="CollisionTest_asystems.vez10_171" status="run" time="0" classname="Scenarios.AsWaypointFollower_2">
      <failure message="CollisionTest"  type=""><!\[CDATA\[
  Actual:   1
  Expected: 0

  Exact Value: CollisionTest = 1\]\]></failure>
    </testcase>
    <testcase name="Duration" status="run" time="44.29674530029297" classname="Scenarios.AsWaypointFollower_2">
  Exact Value: Duration = 74.50000111013651
    </testcase>
  </testsuite>
</testsuites>
```
Conversion code:
```python
import vjunit.vjunit
converter = vjunit.vjunit.VJunit()
converter.convert("junit-results.xml", "out.html")
```
Which resulted in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kpawelczyk/anaconda3/envs/simulator/lib/python3.8/site-packages/vjunit/vjunit.py", line 80, in convert
    testsuites = self.parse(path)
  File "/home/kpawelczyk/anaconda3/envs/simulator/lib/python3.8/site-packages/vjunit/vjunit.py", line 22, in parse
    return self.parse_content(self._load_file(path))
  File "/home/kpawelczyk/anaconda3/envs/simulator/lib/python3.8/site-packages/vjunit/vjunit.py", line 26, in parse_content
    tree = ET.fromstring(content)
  File "/home/kpawelczyk/anaconda3/envs/simulator/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5, column 50
```
According to XML standard CDATA section should not have escaped square braces https://www.w3.org/TR/xml/#sec-cdata-sect.

In this MR I propose to remove escape sequence around CDATA sections. I tested such file and it was converted correctly. 

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.8.5
  * **Unreal Engine version(s):** 4.24
  * **CARLA version:** 0.9.11

#### Possible Drawbacks

None that I can think of.

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/765)

### CODE REVIEW

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AzaelCicero)

**Comment by fabianoboril** [comment]
Can you please update the branch?

**Comment by AzaelCicero** [comment]
Branch updated.

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AzaelCicero)

**Pull request merged**
