### PR TITLE
Type-hint comments for CarlaDataProvider

### PR DESCRIPTION
**Pull request by Daraan**
#### Description

This PR only adds comments that can be picked up by [mypy](https://mypy.readthedocs.io/en/stable/index.html) for example and does not modify any code.

So far only type-hints for the CarlaDataProvider so that they can be picked up by IDE extensions to allow for better code completion.

TODO:

- [x] What is the correct type hint for  `_global_osc_parameters = {} # type: dict[str, Any]`?
  From what I found from online resources `Any` fits bests, the types I've seen where `[str, Number, ParameterRef]` 
- [x] Decide:
 - A) Strict: Declare variables that are `None` before init / after cleanup, like `_world`, as `carla.World | None`   
 - B) Practical: Use their correct type without None and *assume* initialization and no usage after cleanup.

---

Note: As long as it is no main feature of carla this PR https://github.com/carla-simulator/carla/pull/7009 adds type-hints for carla.

- - -
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1066)

### CODE REVIEW

**Review by PabloVD — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1066)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Daraan)

**Comment by Daraan** [comment]
Sorry, didn't know that this was a request review button.😅

Any opinion on the AB choices,?

**Comment by PabloVD** [comment]
Thanks for the PR. Given that it is a static class initialized at the beginning, we can ignore `None`s. Therefore, we prefer the Practical B choice.

**Comment by Daraan** [comment]
@PabloVD removed most None values, and increased the type-coverage

**Comment by PabloVD** [comment]
@Daraan thanks for your changes, now we can approve the PR.

**Pull request merged**
