### PR TITLE
Features/traffic signs infraction criterion

### PR DESCRIPTION
**Pull request by germanros1987**
#### Description

New test to detect if an actor has ran a red light

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubunty 16.04
  * **Python version(s):** 3.5.5
  * **Unreal Engine version(s):** NA
  * **CARLA version:** 0.9.4-pre

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/57)

### CODE REVIEW

**Comment by felipecode** [comment]
___
*[srunner/scenariomanager/atomic_scenario_criteria.py, line 619 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/57#-LZuTowR0jjv8FyR9eWL:-LZuTowR0jjv8FyR9eWM:b-v7kxt1) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/aaf6f8a710b9de9f2f9be09f76bec65eabaeb813/srunner/scenariomanager/atomic_scenario_criteria.py#L619)):*
> ```Python
>                 distance = carla.Location(transformed_tv).distance(location)
>                 s = self.length(traffic_light.trigger_volume.extent) + self.length(self._actor.bounding_box.extent)
>                 if distance <= s:
> ```

Isn't there any possibility for bugs when considering just the distance to the traffic light ? Lets say you just passed a green traffic light and it becomes red just after. Do you get penalized ? 

Further, is this distance euclidean or road based ? If it is euclidean it can be that traffic lights from adjacent roads affects you !

**Comment by felipecode** [comment]
___
*[srunner/scenariomanager/atomic_scenario_criteria.py, line 619 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/57#-LZuTowR0jjv8FyR9eWL:-LZura268Or1EQThWdsX:b32w1t) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/aaf6f8a710b9de9f2f9be09f76bec65eabaeb813/srunner/scenariomanager/atomic_scenario_criteria.py#L619)):*
<details><summary><i>Previously, germanros1987 wrote…</i></summary><blockquote>

This is not the distance to the traffic light. This is checking if you are within the area of action of the trigger box. If you pass the trigger box then you won't get penalized.
</blockquote></details>

Ok

**Comment by felipecode** [comment]
:lgtm:

**Comment by germanros1987** [comment]
Merging after the approval of the feature reviewer.

**Pull request merged**
